"use server";
import {revalidatePath} from "next/cache";import sharp from "sharp";
import {requireAdmin} from "@/lib/auth/require-admin";import {getDb} from "@/lib/db";
import {attachGeneratedProductImage,ProductNotFoundError} from "@/lib/products/mutations";
import {editProductImage,OpenAINotConfiguredError,PhotoStudioAIError,PhotoStudioRateLimitError} from "@/lib/photo-studio/openai";
import {parsePhotoStudioRequest,PhotoStudioValidationError,validateSourceImage} from "@/lib/photo-studio/validation";
import {deleteOwnedProduct360Image,ImageValidationError,uploadProduct360Frame,uploadProduct360Source} from "@/lib/products/storage";
import {product360CaptureSlots,readProduct360Sources,type Product360CaptureCount,type Product360Slot} from "@/lib/product-360/types";

export type ProcessImageResult={error?:string;image?:string;contentType?:"image/png";width?:number;height?:number};
export async function processPhotoStudioImageAction(formData:FormData):Promise<ProcessImageResult>{await requireAdmin();try{const file=formData.get("image");if(!(file instanceof File))throw new PhotoStudioValidationError("Rasmni tanlang.");const source=await validateSourceImage(file);const values=Object.fromEntries(formData.entries());if(values.mode==="360")return{error:"360° rejimida real fotosuratlar ishlatiladi."};const{mode,settings}=parsePhotoStudioRequest(values);const result=await editProductImage({...source,mode,settings});return{image:result.bytes.toString("base64"),contentType:result.contentType,width:result.width,height:result.height};}catch(error){if(error instanceof PhotoStudioValidationError)return{error:error.message};if(error instanceof OpenAINotConfiguredError)return{error:"OpenAI API sozlanmagan."};if(error instanceof PhotoStudioRateLimitError)return{error:"So‘rovlar soni vaqtincha cheklangan. Birozdan so‘ng qayta urinib ko‘ring."};if(error instanceof PhotoStudioAIError)return{error:"Rasmni qayta ishlash amalga oshmadi. Qayta urinib ko‘ring."};return{error:"AI xizmatiga ulanishda xatolik yuz berdi."};}}
export async function saveApprovedPhotoStudioImageAction(raw:{productId:string;placement:"main"|"gallery";image:string}):Promise<{error?:string;success?:true}>{await requireAdmin();try{if(!raw||!/^[A-Za-z0-9_-]{1,64}$/.test(raw.productId)||!["main","gallery"].includes(raw.placement)||typeof raw.image!=="string")throw new PhotoStudioValidationError("Saqlash ma’lumotlari noto‘g‘ri.");const bytes=Buffer.from(raw.image,"base64");if(!bytes.length||bytes.length>20*1024*1024||bytes[0]!==0x89||bytes[1]!==0x50||bytes[2]!==0x4e||bytes[3]!==0x47)throw new PhotoStudioValidationError("Tayyor rasm noto‘g‘ri.");if(!await getDb().product.count({where:{id:raw.productId}}))throw new ProductNotFoundError();await attachGeneratedProductImage(raw.productId,new File([bytes],"ai-product.png",{type:"image/png"}),raw.placement);return{success:true};}catch(error){if(error instanceof PhotoStudioValidationError||error instanceof ProductNotFoundError)return{error:error instanceof ProductNotFoundError?"Mahsulot topilmadi.":error.message};return{error:"Rasmni saqlashda xatolik yuz berdi."};}}

const validProduct=(id:string)=>/^[A-Za-z0-9_-]{1,64}$/.test(id);const validSlot=(slot:string):slot is Product360Slot=>/^real-(12-(00[1-9]|01[0-2])|24-(00[1-9]|01\d|02[0-4]))$/.test(slot);
export async function uploadProduct360SourceAction(formData:FormData){await requireAdmin();const productId=String(formData.get("productId")??""),slot=String(formData.get("slot")??"");const file=formData.get("image");if(!validProduct(productId)||!validSlot(slot)||!(file instanceof File))return{error:"Yuklash ma’lumotlari noto‘g‘ri."};try{const db=getDb();if(!await db.product.count({where:{id:productId}}))return{error:"Mahsulot topilmadi."};const previous=await db.product360Asset.findUnique({where:{productId}});if(previous?.status==="PROCESSING")return{error:"Tekshiruvdagi 360° natijani avval bekor qiling."};const sources=readProduct360Sources(previous?.sourceImages),oldUrl=sources[slot],url=await uploadProduct360Source(productId,slot,file),nextSources={...sources,[slot]:url};try{const staleFrames=previous?.frames??[];const asset=await db.product360Asset.upsert({where:{productId},create:{productId,status:"DRAFT",sourceImages:nextSources},update:{status:"DRAFT",sourceImages:nextSources,frames:[],frameCount:0,posterImage:null}});if(oldUrl)await Promise.allSettled([deleteOwnedProduct360Image(oldUrl,productId)]);await Promise.allSettled(staleFrames.filter(Boolean).map(frame=>deleteOwnedProduct360Image(frame,productId)));revalidatePath("/admin/photo-studio");return{asset:{id:asset.id,productId,status:asset.status,sourceImages:nextSources,frames:[],frameCount:0}};}catch(error){await Promise.allSettled([deleteOwnedProduct360Image(url,productId)]);throw error;}}catch(error){if(error instanceof ImageValidationError)return{error:error.message};return{error:"360° manba rasmini saqlashda xatolik yuz berdi."};}}
export async function removeProduct360SourceAction(raw:{productId:string;slot:Product360Slot}){await requireAdmin();if(!raw||!validProduct(raw.productId)||!validSlot(raw.slot))return{error:"O‘chirish ma’lumotlari noto‘g‘ri."};const db=getDb(),asset=await db.product360Asset.findUnique({where:{productId:raw.productId}});if(!asset)return{sourceImages:{}};if(asset.status==="PROCESSING")return{error:"Tekshiruvdagi 360° natijani avval bekor qiling."};const sources=readProduct360Sources(asset.sourceImages),oldUrl=sources[raw.slot];delete sources[raw.slot];await db.product360Asset.update({where:{productId:raw.productId},data:{status:"DRAFT",sourceImages:sources,frames:[],frameCount:0,posterImage:null}});if(oldUrl)await Promise.allSettled([deleteOwnedProduct360Image(oldUrl,raw.productId)]);await Promise.allSettled(asset.frames.filter(Boolean).map(frame=>deleteOwnedProduct360Image(frame,raw.productId)));revalidatePath("/admin/photo-studio");return{sourceImages:sources};}

async function normalizeStoredImage(url:string){const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("Source unavailable");const type=response.headers.get("content-type")?.split(";")[0]??"";if(!["image/png","image/jpeg","image/webp"].includes(type))throw new Error("Invalid source type");const bytes=new Uint8Array(await response.arrayBuffer());if(!bytes.length||bytes.length>10*1024*1024)throw new Error("Invalid source size");return sharp(bytes).rotate().resize(1200,1200,{fit:"contain",background:{r:255,g:255,b:255,alpha:1}}).png().toBuffer();}
export async function normalizeRealProduct360Action(productId:string,count:Product360CaptureCount){await requireAdmin();if(!validProduct(productId)||![12,24].includes(count))return{error:"360° ma’lumotlari noto‘g‘ri."};const db=getDb(),asset=await db.product360Asset.findUnique({where:{productId}});if(!asset)return{error:"360° manbasi topilmadi."};const slots=product360CaptureSlots(count),sources=readProduct360Sources(asset.sourceImages);if(slots.some(item=>!sources[item.slot]))return{error:`${count} ta real fotosurat to‘liq yuklanmagan.`};const claimed=await db.product360Asset.updateMany({where:{productId,status:{in:["DRAFT","FAILED"]}},data:{status:"PROCESSING",frameCount:0,posterImage:null}});if(!claimed.count)return{error:"360° natija allaqachon tekshiruvda yoki tayyor."};const created:string[]=[];try{for(const item of slots){const url=await uploadProduct360Frame(productId,item.position,await normalizeStoredImage(sources[item.slot]!));created.push(url);}const stale=asset.frames.filter(Boolean);const updated=await db.product360Asset.update({where:{productId},data:{status:"PROCESSING",frames:created,frameCount:0,posterImage:null}});await Promise.allSettled(stale.map(url=>deleteOwnedProduct360Image(url,productId)));revalidatePath("/admin/photo-studio");return{asset:{id:updated.id,productId,status:updated.status,sourceImages:sources,frames:created,frameCount:0}};}catch{await Promise.allSettled(created.map(url=>deleteOwnedProduct360Image(url,productId)));await db.product360Asset.update({where:{productId},data:{status:"FAILED",frames:[],frameCount:0,posterImage:null}});return{error:"Kadrlarni normallashtirishda xatolik yuz berdi."};}}
export async function approveProduct360Action(productId:string,count:Product360CaptureCount){await requireAdmin();if(!validProduct(productId)||![12,24].includes(count))return{error:"Mahsulot noto‘g‘ri."};const db=getDb(),asset=await db.product360Asset.findUnique({where:{productId},include:{product:{select:{slug:true}}}});const slots=product360CaptureSlots(count),sources=asset?readProduct360Sources(asset.sourceImages):{};if(!asset||asset.status!=="PROCESSING"||asset.frames.length!==count||asset.frames.some(frame=>!frame)||slots.some(item=>!sources[item.slot]))return{error:`${count} ta real kadr to‘liq tayyor emas.`};const checks=await Promise.all(asset.frames.map(url=>fetch(url,{method:"HEAD",cache:"no-store"}).then(response=>response.ok).catch(()=>false)));if(checks.some(ok=>!ok))return{error:"Saqlangan kadrlardan biri mavjud emas."};await db.product360Asset.update({where:{productId},data:{status:"READY",frameCount:count,posterImage:asset.frames[0]}});revalidatePath(`/products/${asset.product.slug}`);revalidatePath("/admin/photo-studio");return{success:true as const};}
export async function discardProduct360DraftAction(productId:string){await requireAdmin();if(!validProduct(productId))return{error:"Mahsulot noto‘g‘ri."};const db=getDb(),asset=await db.product360Asset.findUnique({where:{productId}});if(!asset)return{error:"360° ma’lumoti topilmadi."};if(asset.status==="READY")return{error:"Tayyor 360° natijani bu amaldan foydalanib o‘chirib bo‘lmaydi."};const sources=readProduct360Sources(asset.sourceImages),legacyAi=asset.frames.length===8&&Object.keys(sources).length<12;const remove=legacyAi?[asset.frames[1],asset.frames[3],asset.frames[5],asset.frames[7]].filter(Boolean):asset.frames.filter(Boolean);const frames=legacyAi?asset.frames.map((url,index)=>index%2===1?"":url):[];await db.product360Asset.update({where:{productId},data:{status:"DRAFT",frames,frameCount:0,posterImage:null}});await Promise.allSettled(remove.map(url=>deleteOwnedProduct360Image(url,productId)));revalidatePath("/admin/photo-studio");return{asset:{id:asset.id,productId,status:"DRAFT" as const,sourceImages:sources,frames,frameCount:0},legacyAi};}
