export type ProductCategory = { id: string; name: string; slug: string; isActive: boolean; order: number; productCount?: number };
export type ProductAvailability = "available" | "order";
export type ProductSpecification = { id: string; name: string; value: string; mobileOrder?: number };
export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  model: string;
  categoryId?: string;
  category: string;
  categoryName?: string;
  priceUsd?: string | null;
  badge: string;
  image: string | null;
  images?: string[];
  shortDescription?: string;
  description?: string;
  descriptionBullets?: string[];
  specifications?: ProductSpecification[];
  applications?: { id: string; label: string }[];
  tags?: string[];
  specs: string[];
  availability: ProductAvailability;
  order: number;
  isVisible: boolean;
  seoTitle?: string;
  seoDescription?: string;
  updatedAt?: string;
};
