import "server-only";
import { requireAdmin } from "@/lib/auth/require-admin";
import { getDb } from "@/lib/db";
import type { Lead as DbLead,SalesAgent } from "@/generated/prisma/client";
import type { ConversationMessage,Lead,LeadSource,LeadStatus } from "./types";
const statusMap={NEW:"new",REVIEWING:"reviewing",CONTACTED:"contacted",COMPLETED:"completed",IN_PROGRESS:"in_progress",WON:"won",LOST:"lost"} as const;
const sourceMap={CONTACT_FORM:"contact_form",MADINA:"madina",PRODUCT:"product",PROJECT:"project",HOME_CTA:"home_cta",OTHER:"other"} as const;
function conversation(value:unknown):ConversationMessage[]{if(!Array.isArray(value))return[];return value.flatMap((item,index)=>item&&typeof item==="object"&&"role" in item&&"text" in item&&(item.role==="madina"||item.role==="customer")&&typeof item.text==="string"?[{id:`message-${index}`,role:item.role,text:item.text}]:[]);}
function seller(agent:SalesAgent|null){return agent?[agent.firstName,agent.lastName].filter(Boolean).join(" "):"";}
function mapLead(row:DbLead&{assignedAgent:SalesAgent|null}):Lead{const now=new Date(),date=new Date(row.createdAt),formatDay=(value:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tashkent"}).format(value),today=formatDay(now),day=formatDay(date),yesterday=formatDay(new Date(now.getTime()-86400000));return{id:row.id,customerName:row.customerName||"Noma’lum mijoz",phone:row.phone||"",telegram:row.telegram||"",requestType:row.requestType,product:row.product||"",dimensions:row.dimensions||"",capacity:row.capacity||"",temperature:row.temperature||"",region:row.region||"",dateLabel:new Intl.DateTimeFormat("uz-UZ",{timeZone:"Asia/Tashkent",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(date),dateGroup:day===today?"today":day===yesterday?"yesterday":"week",status:statusMap[row.status] as LeadStatus,source:sourceMap[row.source] as LeadSource,isUnread:row.status==="NEW",additional:row.notes||"",summary:row.aiSummary||"",conversation:conversation(row.chatHistory),managerNote:row.managerNote||"",createdAt:row.createdAt.toISOString(),assignedAgentName:seller(row.assignedAgent),claimedAt:row.claimedAt?row.claimedAt.toISOString():"",privateDeliveryFailed:Boolean(row.telegramPrivateDeliveryFailedAt)};}
export async function getAdminLeads(){await requireAdmin();return(await getDb().lead.findMany({orderBy:{createdAt:"desc"},include:{assignedAgent:true}})).map(mapLead);}
