import "server-only";
type SafeLead={id:string;customerName:string|null;region:string|null;requestType:string;product:string|null;temperature:string|null;source?:string};
const lines=(items:Array<string|false|null|undefined>)=>items.filter(Boolean).join("\n");
function groupSafe(value:string|null){if(!value)return null;const compact=value.replace(/[\s().-]/g,"");if(/@\w{3,}|\+?\d{7,}/.test(compact))return null;return value.slice(0,160);}
export function agentName(agent:{firstName:string;lastName:string|null;telegramUsername:string|null}){return [agent.firstName,agent.lastName].filter(Boolean).join(" ")||agent.telegramUsername||"Sotuvchi";}
export function newLeadGroupText(lead:SafeLead){const name=groupSafe(lead.customerName),region=groupSafe(lead.region),request=groupSafe(lead.requestType),product=groupSafe(lead.product),temperature=groupSafe(lead.temperature),consultation=lead.source==="PRODUCT_CONSULTATION";return lines([consultation?"🔵 YANGI MASLAHAT SO‘ROVI":"🔵 YANGI MIJOZ","",name&&`👤 ${name}`,region&&`📍 ${region}`,`❄️ ${request||"Yangi murojaat"}`,product&&`🍎 Mahsulot: ${product}`,temperature&&`🌡 ${temperature}`,consultation&&"Manba: Mahsulot sahifasi"]);}
export function claimedLeadGroupText(lead:SafeLead,seller:string){const name=groupSafe(lead.customerName),region=groupSafe(lead.region),request=groupSafe(lead.requestType),product=groupSafe(lead.product),temperature=groupSafe(lead.temperature);return lines(["🔒 MIJOZ OLINDI","",name&&`👤 ${name}`,region&&`📍 ${region}`,`❄️ ${request||"Yangi murojaat"}`,product&&`🍎 ${product}`,temperature&&`🌡 ${temperature}`,"",`🙋 Sotuvchi: ${groupSafe(seller)||"Sotuvchi"}`]);}
export function privateLeadText(lead:SafeLead&{phone:string|null;telegram:string|null;dimensions:string|null;capacity:string|null;notes:string|null}){return lines(["🔐 SIZGA YANGI MIJOZ BIRIKTIRILDI","",`👤 Mijoz: ${lead.customerName||"Ko‘rsatilmagan"}`,lead.phone&&`☎️ Telefon: ${lead.phone}`,lead.telegram&&`Telegram: ${lead.telegram}`,lead.region&&`📍 Hudud: ${lead.region}`,`❄️ So‘rov: ${lead.requestType}`,lead.product&&`🍎 Mahsulot: ${lead.product}`,lead.temperature&&`🌡 Harorat: ${lead.temperature}`,lead.dimensions&&`O‘lcham: ${lead.dimensions}`,lead.capacity&&`Sig‘im: ${lead.capacity}`,lead.notes&&`Izoh: ${lead.notes}`]);}
export function welcomeText(name:string){return `👋 Xush kelibsiz, ${name}!\n\nBUYUK KARAVAN mijozlari bilan ishlash uchun @BkmadinaAibot botini oching va START tugmasini bosing.\n\nRo‘yxatdan o‘tgandan so‘ng yangi mijozlarni olish imkoniga ega bo‘lasiz.`;}
export function registrationText(name:string,approved:boolean){return approved?`Assalomu alaykum, ${name}! 👋\n\nSiz BKLead tizimida faol sotuvchisiz.`:`Assalomu alaykum, ${name}! 👋\n\nBKLead savdo tizimiga ro‘yxatdan o‘tdingiz.\n\nTasdiqlangandan so‘ng yangi mijozlarni olish imkoniga ega bo‘lasiz.`;}
