"use server";
import { redirect } from "next/navigation";
import { createProject,deleteProject,ProjectNotFoundError,ProjectSlugError,toggleProjectVisibility,updateProject,type ProjectImageInput } from "@/lib/projects/mutations";
import { ProjectImageError } from "@/lib/projects/storage";
import { projectSchema } from "@/lib/projects/validation";
import { requireAdmin } from "@/lib/auth/require-admin";
import { writeAudit } from "@/lib/audit/service";
export async function saveProjectAction(id:string|null,input:unknown,images:ProjectImageInput[]){const actor=await requireAdmin(),parsed=projectSchema.safeParse(input);if(!parsed.success)return{error:parsed.error.issues[0]?.message||"Ma'lumotlarni tekshiring."};try{const row=id?await updateProject(id,parsed.data,images):await createProject(parsed.data,images);await writeAudit(actor,{action:id?"UPDATE":"CREATE",entityType:"PROJECT",entityId:row.id,entityName:row.title,summary:id?"Loyihani yangiladi":"Loyiha yaratdi",after:{title:row.title,slug:row.slug,isVisible:row.isVisible,isFeatured:row.isFeatured,imageCount:row.images.length}});}catch(e){if(e instanceof ProjectSlugError)return{error:"Bu slug band."};if(e instanceof ProjectImageError)return{error:e.message};return{error:"Loyihani saqlab bo'lmadi."};}redirect(`/admin/projects?saved=${id?"updated":"created"}`);}
export async function deleteProjectAction(id:string){const actor=await requireAdmin();try{await deleteProject(id);await writeAudit(actor,{action:"DELETE",entityType:"PROJECT",entityId:id,summary:"Loyihani o'chirdi"});return{};}catch(e){return{error:e instanceof ProjectNotFoundError?"Loyiha topilmadi.":"Loyihani o'chirib bo'lmadi."};}}
export async function toggleProjectVisibilityAction(id:string){const actor=await requireAdmin();try{const row=await toggleProjectVisibility(id);await writeAudit(actor,{action:"STATUS_CHANGE",entityType:"PROJECT",entityId:row.id,entityName:row.title,summary:row.isVisible?"Loyihani saytda ko'rsatdi":"Loyihani saytda yashirdi",after:{isVisible:row.isVisible}});return{};}catch{return{error:"Holatni yangilab bo'lmadi."};}}
