import { ArrowDown, ArrowRight, Building2, Camera as Instagram, CircuitBoard, DoorClosed, Grid2X2, Mouse, PanelsTopLeft, Send, Snowflake, Waves } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { initialHomeContent, type HomeContent } from "@/data/admin-home";
import type { Product } from "@/lib/products/types";
import { Header } from "./navigation";
import { Selector } from "./selector";
import { HomeMotion } from "./motion";

function Brand({ light = false }: { light?: boolean }) { return <span className={`brand ${light ? "light" : ""}`}><span className="brand-mark" aria-hidden="true">✳</span> BUYUK KARAVAN</span>; }
function Button({ children, href, variant = "blue", arrow = false, className = "" }: { children: React.ReactNode; href: string; variant?: "blue" | "white" | "outline" | "outline-light"; arrow?: boolean; className?: string }) { return <a href={href} className={`button button-${variant} ${className}`}>{children}{arrow && <ArrowRight size={16} aria-hidden="true" />}</a>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <div className={`section-heading ${light ? "light" : ""}`}><p className="eyebrow">{eyebrow}</p><h2>{children}</h2></div>; }
const iconMap = { room: PanelsTopLeft, compressor: CircuitBoard, snow: Snowflake, building: Building2, pulse: Waves, condenser: PanelsTopLeft, panel: Grid2X2, door: DoorClosed, pipe: Waves };
function IndustrialIcon({ icon, size = 38 }: { icon: keyof typeof iconMap; size?: number }) { const Icon = iconMap[icon]; return <Icon size={size} strokeWidth={1.7} aria-hidden="true" />; }

function HeroContourLight() {
  return <>
    <svg className="hero-contour-light hero-contour-desktop" viewBox="0 0 580 580" aria-hidden="true">
      <defs><radialGradient id="hero-ice-glow"><stop stopColor="#d9f8ff" stopOpacity=".8"/><stop offset=".28" stopColor="#99e9ff" stopOpacity=".38"/><stop offset="1" stopColor="#99e9ff" stopOpacity="0"/></radialGradient></defs>
      <path id="hero-contour-desktop-path" d="M155 120 H425 Q460 120 460 155 V425 Q460 460 425 460 H155 Q120 460 120 425 V155 Q120 120 155 120 Z" fill="none"/>
      <g className="hero-contour-trail"><circle r="19" fill="url(#hero-ice-glow)"/></g>
      <g className="hero-contour-beacon"><circle r="30" fill="url(#hero-ice-glow)"/><circle r="3" fill="#d9f8ff"/></g>
    </svg>
    <svg className="hero-contour-light hero-contour-mobile" viewBox="0 0 350 300" aria-hidden="true">
      <defs><radialGradient id="hero-ice-glow-mobile"><stop stopColor="#d9f8ff" stopOpacity=".7"/><stop offset=".32" stopColor="#99e9ff" stopOpacity=".3"/><stop offset="1" stopColor="#99e9ff" stopOpacity="0"/></radialGradient></defs>
      <path id="hero-contour-mobile-path" d="M35 1 H315 Q349 1 349 35 V265 Q349 299 315 299 H35 Q1 299 1 265 V35 Q1 1 35 1 Z" fill="none"/>
      <g className="hero-contour-beacon"><circle r="22" fill="url(#hero-ice-glow-mobile)"/><circle r="2.5" fill="#d9f8ff"/></g>
    </svg>
  </>;
}
function Hero({content}:{content:HomeContent["hero"]}) { const lines=content.headline.split("\n"); return <section className="hero" style={content.image?{backgroundImage:`linear-gradient(#092741c7,#092741c7),url(${content.image})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}><div className="hero-grid" aria-hidden="true"/><div className="hero-room room-back" aria-hidden="true"/><div className="hero-room room-front" aria-hidden="true"><HeroContourLight/></div><div className="container hero-content"><div className="hero-copy"><p className="eyebrow hero-eyebrow">{content.eyebrow}</p><h1><span className="hero-title-desktop">{lines.map((line,index)=><span key={index}>{line}{index<lines.length-1&&<br/>}</span>)}</span><span className="hero-title-mobile">{lines.map((line,index)=><span className="hero-title-line" key={index}>{line}</span>)}</span></h1><p className="hero-subtitle">{content.subtitle}</p><div className="hero-actions"><Link href="/products" className="button button-white">{content.primaryButton} <ArrowRight size={16} aria-hidden="true"/></Link><Button href="#loyihalar" variant="outline-light">{content.secondaryButton}</Button></div></div><div className="hero-temp"><small>Harorat diapazoni</small><strong>{content.minimum} <span>→</span> {content.maximum}</strong><i/></div><div className="hero-scroll"><Mouse size={19}/><span>Pastga aylantiring</span><ArrowDown size={13}/></div></div></section>; }
function Solutions({content}:{content:HomeContent["solutions"]}) { return <section className="solutions-section" id="yechimlar"><div className="container"><Heading eyebrow={content.eyebrow}>{content.title}</Heading><div className="solutions-list">{content.items.filter(s => s.isVisible).sort((a,b)=>a.order-b.order).map(item => <article className="solution-row" key={item.id}><span className="solution-number">{String(item.order).padStart(2,"0")}</span><div className="solution-copy"><h3>{item.title}</h3><p>{item.description}</p></div><div className="solution-image">{item.image?<Image unoptimized src={item.image} alt="" fill sizes="240px"/>:<IndustrialIcon icon={(item.icon in iconMap?item.icon:"room") as keyof typeof iconMap} size={54}/>}</div></article>)}</div></div></section>; }
const productIcons:Record<string,keyof typeof iconMap>={compressors:"compressor",evaporators:"pulse",condensers:"condenser",chillers:"snow",panels:"panel",doors:"door",pipes:"pipe",accessories:"compressor"};
function Equipment({content,products}:{content:HomeContent["featuredProducts"];products:Product[]}) { const ids=content.items.filter(item=>item.isVisible).sort((a,b)=>a.order-b.order).map(item=>item.productId);const selected=ids.map(id=>products.find(product=>product.id===id)).filter((item):item is Product=>Boolean(item));const shown=selected.length?selected:products.slice(0,7);return <section className="equipment-section" id="mahsulotlar"><div className="container"><div className="section-top"><Heading eyebrow={content.eyebrow} light>{content.title}</Heading><Button href="/products" variant="outline-light" arrow className="desktop-only">Barcha mahsulotlarni ko‘rish</Button></div>{content.description&&<p>{content.description}</p>}<div className="equipment-grid">{shown.map(item => <Link href={`/products/${item.slug}`} className={`equipment-card equipment-${item.category}`} key={item.id}><IndustrialIcon icon={productIcons[item.category]??"compressor"} size={32}/><div><h3>{item.name}</h3><p>{item.model}</p></div></Link>)}</div><Button href="/products" variant="outline-light" className="mobile-only equipment-all">Barcha mahsulotlarni ko‘rish</Button></div></section>; }
const ranges = [{ value:"−40° / −18°",label:"Shok muzlatish"},{value:"−18° / −5°",label:"Chuqur muzlatish"},{value:"−5° / 0°",label:"Muzlatish chegarasi"},{value:"0° / +5°",label:"Sovutish va saqlash"}];
function Temperature({content}:{content:HomeContent["temperature"]}) { const labels=content.labels.split(/[·\n]/).map(item=>item.trim()).filter(Boolean);return <section className="temperature-section"><div className="container temperature-layout"><div className="temperature-copy"><p className="eyebrow">{content.title}</p><div className="temperature-values"><span>{content.minimum}</span><i>→</i><span>{content.maximum}</span></div><p>{content.description}</p></div><div className="temperature-scale"><div className="scale-line" aria-hidden="true"><i/><i/><i/><i/></div><div className="range-grid">{ranges.map((range,index) => <div key={range.value}><strong>{range.value}</strong><span>{labels[index]??range.label}</span></div>)}</div></div></div></section>; }
function Projects({content}:{content:HomeContent["projects"]}) { return <section className="projects-section" id="loyihalar"><div className="container"><div className="section-top"><Heading eyebrow={content.eyebrow}>{content.title}</Heading><Button href="#aloqa" variant="outline" className="desktop-only">Barcha loyihalar</Button></div><div className="projects-grid">{content.items.filter(p=>p.isVisible).sort((a,b)=>a.order-b.order).map((project,index) => <article className={`project-card project-${index+1}`} style={project.image?{backgroundImage:`linear-gradient(#071f3473,#071f3473),url(${project.image})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined} key={project.id}>{!project.image&&index===0&&<span className="project-placeholder">[Loyiha surati]</span>}<div className="project-info"><h3>{project.title}</h3><strong>{project.temperature}</strong>{project.description && <p>{project.description}</p>}</div></article>)}</div><Button href="#aloqa" variant="outline" className="mobile-only projects-all">Barcha loyihalar</Button></div></section>; }
function Reasons({content}:{content:HomeContent["reasons"]}) { return <section className="reasons-section" id="biz-haqimizda"><div className="container reasons-layout"><Heading eyebrow={content.eyebrow}>{content.headline.split("\n").map((line,index)=><span key={index}>{line}{index<content.headline.split("\n").length-1&&<br/>}</span>)}</Heading><div className="reasons-list">{content.items.filter(item=>item.isVisible).sort((a,b)=>a.order-b.order).map((reason,index)=><article className="reason-row" key={reason.id}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{reason.title}</h3><p>{reason.description}</p></div></article>)}</div></div></section>; }
function Consultation({content}:{content:HomeContent["cta"]}) { return <section className="consultation-section"><div className="consultation-rings" aria-hidden="true"/><div className="container consultation-content"><h2>{content.headline}</h2><p>{content.description}</p><div className="consultation-actions"><Button href="#aloqa" variant="white">{content.primaryButton}</Button><Button href="#aloqa" variant="outline-light">{content.secondaryButton}</Button></div></div></section>; }
function Footer({ onProducts = false, content = initialHomeContent.footer }: { onProducts?: boolean; content?:HomeContent["footer"] }) {
  const homeLink = (hash: string) => onProducts ? `/${hash}` : hash;
  return <footer className="site-footer" id="aloqa">
    <div className="container footer-grid">
      <div className="footer-about"><Brand light/><p>{content.companyDescription}</p></div>
      <div className="footer-column"><h3>Navigatsiya</h3><a href={homeLink("#top")}>Bosh sahifa</a><a href={homeLink("#yechimlar")}>Sovutish kameralari</a><a href={homeLink("#loyihalar")}>Loyihalar</a><a href={homeLink("#biz-haqimizda")}>Biz haqimizda</a></div>
      <div className="footer-column"><h3>Mahsulotlar</h3><Link href="/products">Kompressorlar</Link><Link href="/products">Evaporatorlar</Link><Link href="/products">Kondensatorlar</Link><Link href="/products">Sandwich panellar</Link></div>
      <div className="footer-column footer-contact"><h3>Aloqa</h3><p>{content.location}</p><p>{content.phone}</p><p>{content.telegram}</p><div className="socials"><a href={`https://instagram.com/${content.instagram.replace(/^@/,"")}`} aria-label="Instagram"><Instagram size={17}/></a><a href={`https://t.me/${content.telegram.replace(/^@/,"")}`} aria-label="Telegram"><Send size={17}/></a></div></div>
    </div>
    <div className="container footer-bottom"><span>© 2026 Buyuk Karavan MChJ. Barcha huquqlar himoyalangan.</span><span>{content.location}</span></div>
    <div className="container footer-admin-row"><span>© 2026 BUYUK KARAVAN</span><span aria-hidden="true">·</span><Link href="/admin">Admin</Link></div>
  </footer>;
}
export function HomePage({content=initialHomeContent,products=[]}:{content?:HomeContent;products?:Product[]}) { return <><Header/><main>{content.hero.isVisible&&<Hero content={content.hero}/>} {content.selector.isVisible&&<Selector content={content.selector}/>} {content.solutions.isVisible&&<Solutions content={content.solutions}/>} {content.featuredProducts.isVisible&&<Equipment content={content.featuredProducts} products={products}/>} {content.temperature.isVisible&&<Temperature content={content.temperature}/>} {content.projects.isVisible&&<Projects content={content.projects}/>} {content.reasons.isVisible&&<Reasons content={content.reasons}/>} {content.cta.isVisible&&<Consultation content={content.cta}/>}</main>{content.footer.isVisible&&<Footer content={content.footer}/>}<HomeMotion/></>; }
export { Footer };
