import { ArrowDown, ArrowRight, Building2, Camera as Instagram, CircuitBoard, DoorClosed, Grid2X2, Mouse, PanelsTopLeft, Send, Snowflake, Waves } from "lucide-react";
import { equipment, projects, reasons, solutions } from "@/data/home";
import { Header } from "./navigation";
import { Selector } from "./selector";
import { HomeMotion } from "./motion";

function Brand({ light = false }: { light?: boolean }) { return <span className={`brand ${light ? "light" : ""}`}><span className="brand-mark" aria-hidden="true">✳</span> BUYUK KARAVAN</span>; }
function Button({ children, href, variant = "blue", arrow = false, className = "" }: { children: React.ReactNode; href: string; variant?: "blue" | "white" | "outline" | "outline-light"; arrow?: boolean; className?: string }) { return <a href={href} className={`button button-${variant} ${className}`}>{children}{arrow && <ArrowRight size={16} aria-hidden="true" />}</a>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <div className={`section-heading ${light ? "light" : ""}`}><p className="eyebrow">{eyebrow}</p><h2>{children}</h2></div>; }
const iconMap = { room: PanelsTopLeft, compressor: CircuitBoard, snow: Snowflake, building: Building2, pulse: Waves, condenser: PanelsTopLeft, panel: Grid2X2, door: DoorClosed, pipe: Waves };
function IndustrialIcon({ icon, size = 38 }: { icon: keyof typeof iconMap; size?: number }) { const Icon = iconMap[icon]; return <Icon size={size} strokeWidth={1.7} aria-hidden="true" />; }

function Hero() { return <section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-room room-back" aria-hidden="true"/><div className="hero-room room-front" aria-hidden="true"/><div className="hero-glow" aria-hidden="true"/><div className="container hero-content"><div className="hero-copy"><p className="eyebrow hero-eyebrow">Sanoat sovutish tizimlari</p><h1><span className="hero-title-desktop">SOVUQLIKNI<br/>BIZ BOSHQARAMIZ</span><span className="hero-title-mobile"><span className="hero-title-line">SOVUQLIKNI BIZ</span><span className="hero-title-line">BOSHQARAMIZ</span></span></h1><p className="hero-subtitle">−40°C dan +5°C gacha professional sovutish yechimlari</p><div className="hero-actions"><Button href="#aloqa" variant="white" arrow>Bepul hisob-kitob</Button><Button href="#loyihalar" variant="outline-light">Loyihalarni ko‘rish</Button></div></div><div className="hero-temp"><small>Harorat diapazoni</small><strong>−40° <span>→</span> +5°C</strong><i/></div><div className="hero-scroll"><Mouse size={19}/><span>Pastga aylantiring</span><ArrowDown size={13}/></div></div></section>; }
function Solutions() { return <section className="solutions-section" id="yechimlar"><div className="container"><Heading eyebrow="Yechimlar">Sovutish yechimlari</Heading><div className="solutions-list">{solutions.filter(s => s.isVisible).map(item => <article className="solution-row" key={item.id}><span className="solution-number">{String(item.order).padStart(2,"0")}</span><div className="solution-copy"><h3>{item.title}</h3><p>{item.description}</p></div><div className="solution-image"><IndustrialIcon icon={item.icon} size={54}/></div></article>)}</div></div></section>; }
function Equipment() { return <section className="equipment-section" id="mahsulotlar"><div className="container"><div className="section-top"><Heading eyebrow="Mahsulotlar" light>Sovutish uskunalari ekotizimi</Heading><Button href="#aloqa" variant="outline-light" arrow className="desktop-only">Barcha mahsulotlarni ko‘rish</Button></div><div className="equipment-grid">{equipment.filter(e => e.isVisible).map(item => <div className={`equipment-card equipment-${item.id}`} key={item.id}><IndustrialIcon icon={item.icon} size={32}/><div><h3>{item.title}</h3>{item.subtitle && <p>{item.subtitle}</p>}</div></div>)}</div><Button href="#aloqa" variant="outline-light" className="mobile-only equipment-all">Barcha mahsulotlarni ko‘rish</Button></div></section>; }
const ranges = [{ value:"−40° / −18°",label:"Shok muzlatish"},{value:"−18° / −5°",label:"Chuqur muzlatish"},{value:"−5° / 0°",label:"Muzlatish chegarasi"},{value:"0° / +5°",label:"Sovutish va saqlash"}];
function Temperature() { return <section className="temperature-section"><div className="container temperature-layout"><div className="temperature-copy"><p className="eyebrow">Muhandislik aniqligi</p><div className="temperature-values"><span>−40°C</span><i>→</i><span>+5°C</span></div><p>Har bir mahsulot uchun to‘g‘ri harorat. Har bir loyiha uchun to‘g‘ri yechim.</p></div><div className="temperature-scale"><div className="scale-line" aria-hidden="true"><i/><i/><i/><i/></div><div className="range-grid">{ranges.map(range => <div key={range.value}><strong>{range.value}</strong><span>{range.label}</span></div>)}</div></div></div></section>; }
function Projects() { return <section className="projects-section" id="loyihalar"><div className="container"><div className="section-top"><Heading eyebrow="Portfolio">Amalga oshirilgan loyihalar</Heading><Button href="#aloqa" variant="outline" className="desktop-only">Barcha loyihalar</Button></div><div className="projects-grid">{projects.filter(p => p.isVisible).map((project,index) => <article className={`project-card project-${index+1}`} key={project.id}>{index===0 && <span className="project-placeholder">[Loyiha surati]</span>}<div className="project-info"><h3>{project.title}</h3><strong>{project.temperature}</strong>{project.description && <p>{project.description}</p>}</div></article>)}</div><Button href="#aloqa" variant="outline" className="mobile-only projects-all">Barcha loyihalar</Button></div></section>; }
function Reasons() { return <section className="reasons-section" id="biz-haqimizda"><div className="container reasons-layout"><Heading eyebrow="Nima uchun biz">Avval maslahat.<br/>Keyin yechim.</Heading><div className="reasons-list">{reasons.map((reason,index)=><article className="reason-row" key={reason.id}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{reason.title}</h3><p>{reason.description}</p></div></article>)}</div></div></section>; }
function Consultation() { return <section className="consultation-section"><div className="consultation-rings" aria-hidden="true"/><div className="container consultation-content"><h2>Sovutish loyihangizni<br/> birgalikda hisoblaymiz</h2><p>Talabingizni ayting — mos uskunalar va sovutish yechimini<br className="desktop-break"/> aniqlashga yordam beramiz.</p><div className="consultation-actions"><Button href="#aloqa" variant="white">Bepul hisob-kitob olish</Button><Button href="#aloqa" variant="outline-light">Mutaxassis bilan bog‘lanish</Button></div></div></section>; }
function Footer() { return <footer className="site-footer" id="aloqa"><div className="container footer-grid"><div className="footer-about"><Brand light/><p>Namangan shahridan — sanoat sovutish agregatlari va kompressor uskunalari bo‘yicha professional yechimlar.</p></div><div className="footer-column"><h3>Navigatsiya</h3><a href="#top">Bosh sahifa</a><a href="#yechimlar">Sovutish kameralari</a><a href="#loyihalar">Loyihalar</a><a href="#biz-haqimizda">Biz haqimizda</a></div><div className="footer-column"><h3>Mahsulotlar</h3><a href="#mahsulotlar">Kompressorlar</a><a href="#mahsulotlar">Evaporatorlar</a><a href="#mahsulotlar">Kondensatorlar</a><a href="#mahsulotlar">Sandwich panellar</a></div><div className="footer-column footer-contact"><h3>Aloqa</h3><p>Namangan, O‘zbekiston</p><p>[Telefon raqami]</p><p>@buyuk_karavan</p><div className="socials"><a href="https://instagram.com/buyuk_karavan" aria-label="Instagram"><Instagram size={17}/></a><a href="https://t.me/buyuk_karavan" aria-label="Telegram"><Send size={17}/></a></div></div></div><div className="container footer-bottom"><span>© 2026 Buyuk Karavan MChJ. Barcha huquqlar himoyalangan.</span><span>Namangan, O‘zbekiston</span></div></footer>; }
export function HomePage() { return <><Header/><main><Hero/><Selector/><Solutions/><Equipment/><Temperature/><Projects/><Reasons/><Consultation/></main><Footer/><HomeMotion/></>; }
