import "server-only";
import { revalidatePath, revalidateTag } from "next/cache";
import { getDb } from "@/lib/db";
import { requireAdmin } from "@/lib/auth/require-admin";
import type { ProjectInput } from "./validation";
import { deleteOwnedProjectImage, ownedProjectImageKey, ProjectImageError, uploadProjectImage } from "./storage";
import { MAX_PROJECT_IMAGES, PROJECT_IMAGE_LIMIT_MESSAGE } from "./image-constants";
export class ProjectNotFoundError extends Error {} export class ProjectSlugError extends Error {}
export type ProjectImageInput={url?:string;file?:File};
function checked(raw:unknown,existing:string[],id?:string){if(!Array.isArray(raw)||raw.length<1)throw new ProjectImageError("Kamida bitta rasm kiriting.");if(raw.length>MAX_PROJECT_IMAGES)throw new ProjectImageError(PROJECT_IMAGE_LIMIT_MESSAGE);return raw.map(x=>{if(!x||typeof x!=="object")throw new ProjectImageError("Rasm ma'lumoti noto'g'ri.");const i=x as ProjectImageInput;if(typeof i.url==="string"&&!i.file&&(existing.includes(i.url)||(id&&ownedProjectImageKey(i.url,id))))return{url:i.url};if(i.file instanceof File&&!i.url)return{file:i.file};throw new ProjectImageError("Rasm ma'lumoti noto'g'ri.");});}
async function upload(id:string,images:ProjectImageInput[]){const uploaded:string[]=[],urls:string[]=[];try{for(const image of images){if(image.url)urls.push(image.url);else if(image.file){const url=await uploadProjectImage(id,image.file);uploaded.push(url);urls.push(url);}}return{urls,uploaded};}catch(e){await Promise.allSettled(uploaded.map(url=>deleteOwnedProjectImage(url,id)));throw e;}}
async function cleanup(id:string,urls:string[]){for(const url of urls){const count=await getDb().project.count({where:{images:{has:url}}});if(!count)await deleteOwnedProjectImage(url,id).catch(()=>console.error("Project image cleanup failed",{projectId:id}));}}
const data=(i:ProjectInput)=>({title:i.title,slug:i.slug,shortDescription:i.shortDescription||null,description:i.description||null,location:i.location||null,temperature:i.temperature||null,capacity:i.capacity||null,category:i.category||null,isVisible:i.isVisible,isFeatured:i.isFeatured,order:i.order});
const unique=(e:unknown)=>!!e&&typeof e==="object"&&"code" in e&&e.code==="P2002";
function refresh(...slugs:string[]){revalidateTag("public-projects","max");revalidatePath("/");revalidatePath("/admin/projects");revalidatePath("/projects/[slug]","page");slugs.forEach(s=>revalidatePath(`/projects/${s}`));}
export async function createProject(input:ProjectInput,raw:unknown){await requireAdmin();const images=checked(raw,[]);try{const row=await getDb().project.create({data:{...data(input),isVisible:false}});try{const result=await upload(row.id,images);try{const saved=await getDb().project.update({where:{id:row.id},data:{images:result.urls,coverImage:result.urls[0],isVisible:input.isVisible}});refresh(saved.slug);return saved;}catch(e){await Promise.allSettled(result.uploaded.map(url=>deleteOwnedProjectImage(url,row.id)));throw e;}}catch(e){await getDb().project.delete({where:{id:row.id}});throw e;}}catch(e){if(unique(e))throw new ProjectSlugError();throw e;}}
export async function createProjectDraft(input:ProjectInput){await requireAdmin();try{return await getDb().project.create({data:{...data(input),isVisible:false,images:[],coverImage:""}});}catch(e){if(unique(e))throw new ProjectSlugError();throw e;}}
export async function updateProject(id:string,input:ProjectInput,raw:unknown){await requireAdmin();const previous=await getDb().project.findUnique({where:{id}});if(!previous)throw new ProjectNotFoundError();const images=checked(raw,previous.images,id);try{const result=await upload(id,images);let saved;try{saved=await getDb().project.update({where:{id},data:{...data(input),images:result.urls,coverImage:result.urls[0]}});}catch(e){await Promise.allSettled(result.uploaded.map(url=>deleteOwnedProjectImage(url,id)));throw e;}refresh(previous.slug,saved.slug);await cleanup(id,previous.images.filter(url=>!saved.images.includes(url)));return saved;}catch(e){if(unique(e))throw new ProjectSlugError();throw e;}}
export async function deleteProject(id:string){await requireAdmin();const row=await getDb().project.findUnique({where:{id}});if(!row)throw new ProjectNotFoundError();await getDb().project.delete({where:{id}});refresh(row.slug);await cleanup(id,row.images);}
export async function toggleProjectVisibility(id:string){await requireAdmin();const row=await getDb().project.findUnique({where:{id}});if(!row)throw new ProjectNotFoundError();const saved=await getDb().project.update({where:{id},data:{isVisible:!row.isVisible}});refresh(row.slug);return saved;}
