"use server";
import {revalidatePath} from "next/cache";
import {requireRole} from "@/lib/auth/require-admin";
import {normalizeUzPhone} from "@/lib/auth/phone";
import {hashPassword} from "@/lib/auth/password";
import {getDb} from "@/lib/db";
import {writeAudit} from "@/lib/audit/service";
import type {AdminRole} from "@/generated/prisma/client";
const roles=new Set<AdminRole>(["SUPER_ADMIN","ADMIN","MANAGER","SELLER"]);
// A SELLER login is linked to one SalesPerson (Sotuv rejasi); other roles never carry a link.
async function sellerLink(role:AdminRole,form:FormData,userId?:string){if(role!=="SELLER")return null;const id=String(form.get("salesPersonId")||"").trim();if(!id)return null;const person=await getDb().salesPerson.findUnique({where:{id},select:{id:true,user:{select:{id:true}}}});if(!person||person.user&&person.user.id!==userId)return undefined;return person.id;}
export async function createAdminUserAction(form:FormData){const actor=await requireRole("SUPER_ADMIN"),name=String(form.get("name")||"").trim(),phone=normalizeUzPhone(String(form.get("phone")||"")),password=String(form.get("password")||""),role=String(form.get("role")||"") as AdminRole;if(!name||name.length>120||!phone||!roles.has(role))return;const salesPersonId=await sellerLink(role,form);if(salesPersonId===undefined)return;const passwordHash=await hashPassword(password);const row=await getDb().adminUser.create({data:{name,phone,passwordHash,role,salesPersonId}});await writeAudit(actor,{action:"CREATE",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:"Admin foydalanuvchi yaratdi",after:{name:row.name,phone:row.phone,role:row.role,isActive:row.isActive,salesPersonId:row.salesPersonId}});revalidatePath("/admin/users");}
export async function updateAdminUserAction(form:FormData){const actor=await requireRole("SUPER_ADMIN"),id=String(form.get("id")||""),name=String(form.get("name")||"").trim(),phone=normalizeUzPhone(String(form.get("phone")||"")),role=String(form.get("role")||"") as AdminRole,isActive=form.get("isActive")==="on";if(!id||!name||!phone||!roles.has(role)||id===actor.id&&!isActive)return;const salesPersonId=await sellerLink(role,form,id);if(salesPersonId===undefined)return;const previous=await getDb().adminUser.findUniqueOrThrow({where:{id}});const row=await getDb().adminUser.update({where:{id},data:{name,phone,role,isActive,salesPersonId}});if(!isActive||previous.role!==role||previous.salesPersonId!==salesPersonId)await getDb().adminSession.deleteMany({where:{userId:id}});await writeAudit(actor,{action:"UPDATE",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:"Admin foydalanuvchini yangiladi",before:{name:previous.name,phone:previous.phone,role:previous.role,isActive:previous.isActive,salesPersonId:previous.salesPersonId},after:{name:row.name,phone:row.phone,role:row.role,isActive:row.isActive,salesPersonId:row.salesPersonId}});revalidatePath("/admin/users");}
export async function reviewAdminRegistrationAction(form:FormData){const actor=await requireRole("SUPER_ADMIN"),id=String(form.get("id")||""),decision=String(form.get("decision")||""),role=String(form.get("role")||"MANAGER") as AdminRole;if(!id||!roles.has(role)||!['approve','reject'].includes(decision))return;const previous=await getDb().adminUser.findUniqueOrThrow({where:{id}});if(previous.approvalStatus!=="PENDING")return;const approved=decision==="approve",row=await getDb().adminUser.update({where:{id},data:{approvalStatus:approved?"APPROVED":"REJECTED",isActive:approved,role:approved?role:previous.role}});if(!approved)await getDb().adminSession.deleteMany({where:{userId:id}});await writeAudit(actor,{action:approved?"APPROVE":"REJECT",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:approved?"Admin ro‘yxatdan o‘tishini tasdiqladi":"Admin ro‘yxatdan o‘tishini rad etdi",before:{approvalStatus:previous.approvalStatus,isActive:previous.isActive,role:previous.role},after:{approvalStatus:row.approvalStatus,isActive:row.isActive,role:row.role}});revalidatePath("/admin/users");}
