"use server";
import {revalidatePath} from "next/cache";
import {requireRole} from "@/lib/auth/require-admin";
import {normalizeUzPhone} from "@/lib/auth/phone";
import {hashPassword} from "@/lib/auth/password";
import {decryptPassword,encryptPassword,isVaultEnabled} from "@/lib/auth/password-vault";
import {checkRemoval,removalPlan,type UserLinks} from "@/lib/auth/user-removal";
import {getDb} from "@/lib/db";
import {writeAudit} from "@/lib/audit/service";
import {checkApproval,SELLER_TAKEN} from "@/lib/auth/approval-rules";
import type {AdminRole} from "@/generated/prisma/client";
import {createLinkCode} from "@/lib/sex/bot";
/** `id` names the row the result belongs to when several rows share one action state. */
export type UserFormState={status:"idle"|"ok"|"error";message:string|null;at:number;id?:string};
const roles=new Set<AdminRole>(["SUPER_ADMIN","ADMIN","MANAGER","SELLER","WORKSHOP"]);
const TAKEN=SELLER_TAKEN;
const ok=(message="Saqlandi",id?:string):UserFormState=>({status:"ok",message,at:Date.now(),id});
const fail=(message:string,id?:string):UserFormState=>({status:"error",message,at:Date.now(),id});
const uniqueTarget=(e:unknown)=>{if(!e||typeof e!=="object"||!("code" in e)||e.code!=="P2002")return null;const target=(e as {meta?:{target?:unknown}}).meta?.target;return String(Array.isArray(target)?target.join(","):target??"");};
const conflictMessage=(e:unknown)=>{const target=uniqueTarget(e);if(target===null)return null;return target.includes("salesPerson")?TAKEN:target.includes("telegramChatId")?"Bu Telegram ID boshqa foydalanuvchiga bog‘langan.":"Bu telefon raqam bilan hisob mavjud.";};
// Telegram is bound with the one-time bot link ("Telegram bog‘lash"); the row form only sends a Telegram id when typed in.
// undefined = leave the binding as it is.
function telegramLink(role:AdminRole,form:FormData):string|null|undefined|{error:string}{if(!form.has("telegramChatId"))return undefined;if(role!=="WORKSHOP")return null;const id=String(form.get("telegramChatId")||"").trim();if(!id)return null;return /^\d{5,20}$/.test(id)?id:{error:"Telegram ID faqat raqamlardan iborat bo‘lsin (botga /myid yozib bilib olinadi)."};}
// A SELLER login is linked to at most one SalesPerson and each SalesPerson to at most one login; other roles never carry a link.
async function sellerLink(role:AdminRole,form:FormData,userId?:string):Promise<string|null|{error:string}>{if(role!=="SELLER")return null;const id=String(form.get("salesPersonId")||"").trim();if(!id)return null;const person=await getDb().salesPerson.findUnique({where:{id},select:{id:true,user:{select:{id:true}}}});if(!person)return{error:"Tanlangan sotuvchi topilmadi."};if(person.user&&person.user.id!==userId)return{error:TAKEN};return person.id;}
export async function createAdminUserAction(_state:UserFormState,form:FormData):Promise<UserFormState>{const actor=await requireRole("SUPER_ADMIN"),name=String(form.get("name")||"").trim(),phone=normalizeUzPhone(String(form.get("phone")||"")),password=String(form.get("password")||""),role=String(form.get("role")||"") as AdminRole;if(!name||name.length>120)return fail("Ismni to‘g‘ri kiriting.");if(!phone)return fail("Telefon raqamini to‘g‘ri kiriting.");if(!roles.has(role))return fail("Rolni tanlang.");if(password.length<12||Buffer.byteLength(password,"utf8")>72)return fail("Parol kamida 12 ta belgidan iborat bo‘lishi kerak.");const salesPersonId=await sellerLink(role,form);if(salesPersonId&&typeof salesPersonId==="object")return fail(salesPersonId.error);const telegramChatId=telegramLink(role,form);if(telegramChatId&&typeof telegramChatId==="object")return fail(telegramChatId.error);try{const passwordHash=await hashPassword(password);const row=await getDb().adminUser.create({data:{name,phone,passwordHash,passwordEncrypted:encryptPassword(password),role,salesPersonId,telegramChatId}});await writeAudit(actor,{action:"CREATE",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:"Admin foydalanuvchi yaratdi",after:{name:row.name,phone:row.phone,role:row.role,isActive:row.isActive,salesPersonId:row.salesPersonId,telegramChatId:row.telegramChatId}});}catch(e){const message=conflictMessage(e);if(message)return fail(message);throw e;}revalidatePath("/admin/users");return ok("Foydalanuvchi yaratildi");}
export async function updateAdminUserAction(_state:UserFormState,form:FormData):Promise<UserFormState>{const actor=await requireRole("SUPER_ADMIN"),id=String(form.get("id")||""),name=String(form.get("name")||"").trim(),phone=normalizeUzPhone(String(form.get("phone")||"")),role=String(form.get("role")||"") as AdminRole,isActive=form.get("isActive")==="on";if(!id)return fail("Foydalanuvchi topilmadi.");if(!name||name.length>120)return fail("Ismni to‘g‘ri kiriting.");if(!phone)return fail("Telefon raqamini to‘g‘ri kiriting.");if(!roles.has(role))return fail("Rolni tanlang.");if(id===actor.id&&!isActive)return fail("O‘zingizni nofaol qila olmaysiz.");const salesPersonId=await sellerLink(role,form,id);if(salesPersonId&&typeof salesPersonId==="object")return fail(salesPersonId.error);const telegramChatId=telegramLink(role,form);if(telegramChatId&&typeof telegramChatId==="object")return fail(telegramChatId.error);const previous=await getDb().adminUser.findUnique({where:{id}});if(!previous)return fail("Foydalanuvchi topilmadi.");try{const nextTelegram=telegramChatId!==undefined?telegramChatId:role==="WORKSHOP"?previous.telegramChatId:previous.role==="WORKSHOP"?null:previous.telegramChatId;const row=await getDb().adminUser.update({where:{id},data:{name,phone,role,isActive,salesPersonId,telegramChatId:nextTelegram}});if(!isActive||previous.role!==role||previous.salesPersonId!==salesPersonId)await getDb().adminSession.deleteMany({where:{userId:id}});await writeAudit(actor,{action:"UPDATE",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:"Admin foydalanuvchini yangiladi",before:{name:previous.name,phone:previous.phone,role:previous.role,isActive:previous.isActive,salesPersonId:previous.salesPersonId,telegramChatId:previous.telegramChatId},after:{name:row.name,phone:row.phone,role:row.role,isActive:row.isActive,salesPersonId:row.salesPersonId,telegramChatId:row.telegramChatId}});}catch(e){const message=conflictMessage(e);if(message)return fail(message);throw e;}revalidatePath("/admin/users");return ok();}
// Approval saves role and SalesPerson link together; both are re-checked here whatever the form sent.
export async function reviewAdminRegistrationAction(_state:UserFormState,form:FormData):Promise<UserFormState>{const actor=await requireRole("SUPER_ADMIN"),id=String(form.get("id")||""),decision=String(form.get("decision")||"");if(!id||!["approve","reject"].includes(decision))return fail("So‘rov noto‘g‘ri.",id);const previous=await getDb().adminUser.findUnique({where:{id}});if(!previous)return fail("Foydalanuvchi topilmadi.",id);if(previous.approvalStatus!=="PENDING")return fail("Bu so‘rov allaqachon ko‘rib chiqilgan.",id);const approved=decision==="approve";let role:AdminRole=previous.role,salesPersonId:string|null=previous.salesPersonId;if(approved){const requested=String(form.get("salesPersonId")||"").trim(),person=requested?await getDb().salesPerson.findUnique({where:{id:requested},select:{id:true,user:{select:{id:true}}}}):null;const checked=checkApproval(String(form.get("role")||""),requested,person&&{id:person.id,userId:person.user?.id??null},id);if("error" in checked)return fail(checked.error,id);role=checked.role;salesPersonId=checked.salesPersonId;}const telegramChatId=approved?telegramLink(role,form):null;if(telegramChatId&&typeof telegramChatId==="object")return fail(telegramChatId.error,id);let row;try{row=await getDb().adminUser.update({where:{id},data:{approvalStatus:approved?"APPROVED":"REJECTED",isActive:approved,role,salesPersonId,...(telegramChatId?{telegramChatId}:{})}});}catch(e){const message=conflictMessage(e);if(message)return fail(message,id);throw e;}if(!approved)await getDb().adminSession.deleteMany({where:{userId:id}});await writeAudit(actor,{action:approved?"APPROVE":"REJECT",entityType:"ADMIN_USER",entityId:row.id,entityName:row.name,summary:approved?"Admin ro‘yxatdan o‘tishini tasdiqladi":"Admin ro‘yxatdan o‘tishini rad etdi",before:{approvalStatus:previous.approvalStatus,isActive:previous.isActive,role:previous.role,salesPersonId:previous.salesPersonId},after:{approvalStatus:row.approvalStatus,isActive:row.isActive,role:row.role,salesPersonId:row.salesPersonId}});revalidatePath("/admin/users");return ok(approved?"Tasdiqlandi":"Rad etildi",id);}

/** "Telegram bog‘lash" next to a WORKSHOP user: a one-time t.me link (15 min) the admin hands to that person. */
export async function createUserTelegramLinkAction(userId:string):Promise<{ok:true;url:string|null;code:string;expiresAt:string}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true,role:true}});if(!user||user.role!=="WORKSHOP")return{ok:false,error:"Faqat seh mas’uli uchun."};const link=await createLinkCode(user.id);await writeAudit(actor,{action:"TELEGRAM_LINK",entityType:"ADMIN_USER",entityId:user.id,entityName:user.name,summary:"Seh mas’uli uchun Telegram bog‘lash havolasini yaratdi"});return{ok:true,...link};}
/** "Uzish": the bot stops sending orders to this person. */
export async function unlinkUserTelegramAction(userId:string):Promise<{ok:true}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true,telegramChatId:true}});if(!user)return{ok:false,error:"Foydalanuvchi topilmadi."};await getDb().adminUser.update({where:{id:userId},data:{telegramChatId:null,telegramLinkCode:null,telegramLinkExpiresAt:null}});await writeAudit(actor,{action:"TELEGRAM_UNLINK",entityType:"ADMIN_USER",entityId:user.id,entityName:user.name,summary:"Telegram bog‘lanishini uzdi",before:{telegramChatId:user.telegramChatId},after:{telegramChatId:null}});revalidatePath("/admin/users");return{ok:true};}

/**
 * A waiting BKLead seller record that a staff / Seh account's /start created by mistake. Deleted only when the Super Admin
 * presses "O‘chirish", only while unapproved and without any activity (leads, sales, marja, links…).
 */
export async function deletePendingAgentAction(agentId:string):Promise<{ok:true}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const agent=await getDb().salesAgent.findUnique({where:{id:agentId},include:{_count:{select:{assignedLeads:true,activities:true,followUps:true,sales:true,marjaTransactions:true,rewardRedemptions:true,referralLinks:true}}}});if(!agent)return{ok:false,error:"Yozuv topilmadi."};if(agent.isApproved)return{ok:false,error:"Tasdiqlangan sotuvchini bu yerdan o‘chirib bo‘lmaydi."};if(Object.values(agent._count).some(count=>count>0))return{ok:false,error:"Bu yozuvda faoliyat bor — o‘chirilmaydi."};await getDb().$transaction([getDb().telegramConversationState.deleteMany({where:{agentId}}),getDb().salesAgent.delete({where:{id:agentId}})]);await writeAudit(actor,{action:"DELETE",entityType:"SALES_AGENT",entityId:agentId,entityName:[agent.firstName,agent.lastName].filter(Boolean).join(" "),summary:"Keraksiz kutilayotgan BKLead sotuvchi yozuvini o‘chirdi",before:{telegramUserId:agent.telegramUserId.toString(),telegramUsername:agent.telegramUsername,isApproved:agent.isApproved}});revalidatePath("/admin/users");return{ok:true};}


// ---- Password view / change (Super Admin) -------------------------------------------------------------
/** ✏️: the Super Admin types a new password; hash for login + encrypted copy for 👁; the user's sessions end. */
export async function setUserPasswordAction(userId:string,password:string):Promise<{ok:true}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");if(typeof password!=="string"||password.length<12||Buffer.byteLength(password,"utf8")>72)return{ok:false,error:"Parol kamida 12 ta belgidan iborat bo‘lsin."};const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true}});if(!user)return{ok:false,error:"Foydalanuvchi topilmadi."};await getDb().$transaction([getDb().adminUser.update({where:{id:user.id},data:{passwordHash:await hashPassword(password),passwordEncrypted:encryptPassword(password),mustPasswordChange:false}}),getDb().adminSession.deleteMany({where:{userId:user.id===actor.id?"__none__":user.id}})]);await writeAudit(actor,{action:"PASSWORD_SET",entityType:"ADMIN_USER",entityId:user.id,entityName:user.name,summary:"Foydalanuvchi parolini o‘zgartirdi (sessiyalari yopildi)"});revalidatePath("/admin/users");return{ok:true};}
/** 👁: decrypted on request only (never with the page), audited; the password itself is never logged. */
export async function revealPasswordAction(userId:string):Promise<{ok:true;password:string}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");if(!isVaultEnabled())return{ok:false,error:"Vercel’da PASSWORD_VIEW_KEY o‘rnating."};const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true,passwordEncrypted:true}});if(!user)return{ok:false,error:"Foydalanuvchi topilmadi."};if(!user.passwordEncrypted)return{ok:false,error:"Parol saqlanmagan — ✏️ bilan yangisini o‘rnating."};let password:string;try{password=decryptPassword(user.passwordEncrypted);}catch{return{ok:false,error:"Parolni ochib bo‘lmadi (kalit o‘zgarganmi?) — ✏️ bilan yangisini o‘rnating."};}await writeAudit(actor,{action:"PASSWORD_VIEW",entityType:"ADMIN_USER",entityId:user.id,entityName:user.name,summary:"Foydalanuvchi parolini ko‘rdi"});return{ok:true,password};}

// ---- Delete / archive (Super Admin) -------------------------------------------------------------------
async function userLinks(userId:string):Promise<UserLinks>{const db=getDb();const [orders,counts]=await Promise.all([db.workshopOrder.count({where:{OR:[{sellerId:userId},{createdById:userId},{acceptedById:userId},{startedById:userId},{issuedById:userId},{receivedById:userId},{cancelledById:userId}]}}),db.adminUser.findUnique({where:{id:userId},select:{_count:{select:{calculations:true,purchasesCreated:true,purchasesReviewed:true,customerSalesCreated:true,customerSalesUpdated:true,approvedSales:true,marjaAdjustments:true,reviewedRedemptions:true,referralLinks:true,aiPriceLists:true,priceChanges:true,createdPhotoAssets:true,attachedPhotoAssets:true,backups:true,auditLogs:true}}}})]);const c=counts?._count;if(!c)return{orders:0,calculations:0,customers:0,sales:0,other:0,activity:0};return{orders,calculations:c.calculations,customers:c.purchasesCreated+c.purchasesReviewed+c.customerSalesCreated+c.customerSalesUpdated,sales:c.approvedSales+c.marjaAdjustments+c.reviewedRedemptions,other:c.referralLinks+c.aiPriceLists+c.priceChanges+c.createdPhotoAssets+c.attachedPhotoAssets+c.backups,activity:c.auditLogs};}
async function removalCheck(actorId:string,userId:string){const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true,role:true,archivedAt:true,telegramChatId:true,salesPersonId:true,isActive:true}});if(!user)return{error:"Foydalanuvchi topilmadi."} as const;const others=await getDb().adminUser.count({where:{role:"SUPER_ADMIN",isActive:true,archivedAt:null,NOT:{id:user.id}}});const check=checkRemoval(actorId,user,others);return check.ok?{user}:{error:check.error};}
/** What "O‘chirish" will do, said before confirming ("Bu foydalanuvchida 12 ta zakaz bor — arxivlanadi"). */
export async function userRemovalPreviewAction(userId:string):Promise<{ok:true;mode:"delete"|"archive";text:string}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const checked=await removalCheck(actor.id,userId);if("error" in checked)return{ok:false,error:checked.error!};const plan=removalPlan(await userLinks(userId));return{ok:true,mode:plan.mode,text:plan.text};}
/** Deletes a user without linked records, otherwise archives them; sessions end and the Telegram link is removed either way. */
export async function removeUserAction(userId:string):Promise<{ok:true;mode:"delete"|"archive"}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const checked=await removalCheck(actor.id,userId);if("error" in checked)return{ok:false,error:checked.error!};const user=checked.user!;const plan=removalPlan(await userLinks(userId));const db=getDb();if(plan.mode==="delete"){await db.$transaction([db.adminSession.deleteMany({where:{userId}}),db.adminUser.delete({where:{id:userId}})]);await writeAudit(actor,{action:"DELETE",entityType:"ADMIN_USER",entityId:userId,entityName:user.name,summary:"Foydalanuvchini o‘chirdi (bog‘langan ma’lumot yo‘q edi)",before:{role:user.role}});}else{await db.$transaction([db.adminUser.update({where:{id:userId},data:{archivedAt:new Date(),isActive:false,telegramChatId:null,telegramLinkCode:null,telegramLinkExpiresAt:null,salesPersonId:null}}),db.adminSession.deleteMany({where:{userId}})]);await writeAudit(actor,{action:"ARCHIVE",entityType:"ADMIN_USER",entityId:userId,entityName:user.name,summary:`Foydalanuvchini arxivladi (${plan.parts.join(", ")})`,before:{isActive:user.isActive,telegramChatId:user.telegramChatId,salesPersonId:user.salesPersonId},after:{archived:true,isActive:false}});}revalidatePath("/admin/users");return{ok:true,mode:plan.mode};}
/** "Qayta tiklash" from the Arxiv filter. Telegram and the seller link are set again by hand. */
export async function restoreUserAction(userId:string):Promise<{ok:true}|{ok:false;error:string}>{const actor=await requireRole("SUPER_ADMIN");const user=await getDb().adminUser.findUnique({where:{id:userId},select:{id:true,name:true,archivedAt:true}});if(!user||!user.archivedAt)return{ok:false,error:"Arxivda bunday foydalanuvchi yo‘q."};await getDb().adminUser.update({where:{id:userId},data:{archivedAt:null,isActive:true}});await writeAudit(actor,{action:"RESTORE",entityType:"ADMIN_USER",entityId:userId,entityName:user.name,summary:"Foydalanuvchini arxivdan qayta tikladi",after:{archived:false,isActive:true}});revalidatePath("/admin/users");return{ok:true};}
