"use client";
import {useActionState,useEffect,useState} from "react";
import {useFormStatus} from "react-dom";
import {createAdminUserAction,reviewAdminRegistrationAction,updateAdminUserAction,type UserFormState} from "./actions";
export type SalesPersonOption={id:string;name:string;userId:string|null};
export type ManagedUser={id:string;name:string;phone:string;role:string;isActive:boolean;approvalStatus:string;salesPersonId:string|null};
const initial:UserFormState={status:"idle",message:null,at:0};
const roleOptions=[["SUPER_ADMIN","Super Admin"],["ADMIN","Administrator"],["MANAGER","Menejer"],["SELLER","Sotuvchi"]] as const;
function SubmitButton({label,pendingLabel="Saqlanmoqda…",className="admin-primary-button admin-user-button",name,value}:{label:string;pendingLabel?:string;className?:string;name?:string;value?:string}){const{pending,data}=useFormStatus();const mine=pending&&(!name||data?.get(name)===value);return <button className={className} disabled={pending} name={name} value={value} aria-busy={mine}>{mine?pendingLabel:label}</button>;}
// Shows "Saqlandi ✓" for 3 seconds after each successful save; errors stay until the next submit.
function Feedback({state}:{state:UserFormState}){const[hiddenAt,setHiddenAt]=useState(0);useEffect(()=>{if(state.status!=="ok")return;const t=setTimeout(()=>setHiddenAt(state.at),3000);return()=>clearTimeout(t);},[state]);if(state.status==="error")return <p className="admin-user-feedback is-error" role="alert">{state.message}</p>;if(state.status==="ok"&&hiddenAt!==state.at)return <span className="admin-user-feedback is-ok" role="status">{state.message} ✓</span>;return null;}
function statusBadge(user:ManagedUser){if(user.approvalStatus==="PENDING")return <span className="sales-agent-status is-pending">Kutilmoqda</span>;if(user.approvalStatus==="APPROVED"&&user.isActive)return <span className="sales-agent-status is-active">Tasdiqlangan</span>;return <span className="sales-agent-status is-inactive">Bloklangan</span>;}
function SellerSelect({role,value,onChange,people,userId}:{role:string;value:string;onChange:(v:string)=>void;people:SalesPersonOption[];userId?:string}){if(role!=="SELLER")return <span className="admin-user-seller is-muted">Faqat sotuvchi roli uchun</span>;const options=people.filter(p=>!p.userId||p.userId===userId);const selected=options.find(p=>p.id===value);return <select className="admin-user-seller" name="salesPersonId" value={value} onChange={e=>onChange(e.target.value)} aria-label="Sotuvchiga bog‘lash" title={selected?.name}><option value="">Sotuvchi tanlanmagan</option>{options.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>;}
export function UserRow({user,people}:{user:ManagedUser;people:SalesPersonOption[]}){const[state,action]=useActionState(updateAdminUserAction,initial);const[name,setName]=useState(user.name),[phone,setPhone]=useState(user.phone),[role,setRole]=useState(user.role),[sellerId,setSellerId]=useState(user.salesPersonId??""),[active,setActive]=useState(user.isActive);return <form action={action} className="admin-user-row admin-managed-user"><input type="hidden" name="id" value={user.id}/><input name="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={120} aria-label="Ism"/><input name="phone" value={phone} onChange={e=>setPhone(e.target.value)} required inputMode="tel" aria-label="Telefon"/><select name="role" value={role} onChange={e=>setRole(e.target.value)} aria-label="Rol">{roleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><SellerSelect role={role} value={sellerId} onChange={setSellerId} people={people} userId={user.id}/><label><input name="isActive" type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Faol</label>{statusBadge(user)}<div className="admin-user-actions"><SubmitButton label="Saqlash"/>{state.status==="ok"&&<Feedback state={state}/>}</div>{state.status==="error"&&<Feedback state={state}/>}</form>;}
export function PendingUserRow({user}:{user:ManagedUser}){const[state,action]=useActionState(reviewAdminRegistrationAction,initial);return <form action={action} className="admin-user-row admin-pending-user"><input type="hidden" name="id" value={user.id}/><div><strong>{user.name}</strong><small>{user.phone}</small></div>{statusBadge(user)}<select name="role" defaultValue="MANAGER" aria-label="Rol"><option value="MANAGER">Menejer</option><option value="ADMIN">Administrator</option></select><SubmitButton name="decision" value="approve" label="Tasdiqlash" pendingLabel="Tasdiqlanmoqda…"/><SubmitButton name="decision" value="reject" label="Rad etish" pendingLabel="Rad etilmoqda…" className="admin-user-button is-danger"/><Feedback state={state}/></form>;}
function CreateUserFields({people}:{people:SalesPersonOption[]}){const[name,setName]=useState(""),[phone,setPhone]=useState(""),[role,setRole]=useState("ADMIN"),[sellerId,setSellerId]=useState("");return <><label className="admin-form-field"><span>Ism</span><input name="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/></label><label className="admin-form-field"><span>Telefon / login</span><input name="phone" value={phone} onChange={e=>setPhone(e.target.value)} required inputMode="tel" placeholder="+998 90 123 45 67"/></label><label className="admin-form-field"><span>Rol</span><select name="role" value={role} onChange={e=>setRole(e.target.value)}>{roleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="admin-form-field"><span>Sotuvchiga bog‘lash</span><SellerSelect role={role} value={sellerId} onChange={setSellerId} people={people}/></label><label className="admin-form-field"><span>Vaqtinchalik parol</span><input name="password" required type="password" minLength={12} maxLength={72} autoComplete="new-password"/></label></>;}
export function CreateUserForm({people}:{people:SalesPersonOption[]}){const[state,action]=useActionState(createAdminUserAction,initial);return <form action={action} className="admin-form-grid"><CreateUserFields key={state.status==="ok"?state.at:0} people={people}/><div className="admin-user-actions"><SubmitButton label="Foydalanuvchi yaratish" pendingLabel="Yaratilmoqda…" className="admin-primary-button"/><Feedback state={state}/></div></form>;}
