"use client";
import { Download, Eye, Plus, Share2, Trash2 } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import { useMemo, useState } from "react";
import { quotationTotals } from "@/lib/calculations/money";
import type { CalculationDraft, ProductProposalOption } from "@/lib/calculations/types";

const num = (value: string) => value === "" ? null : Number.isFinite(Number(value)) ? Number(value) : null;
const money = (value: number | null, currency = "UZS") => value === null ? "—" : currency === "USD" ? `$${new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)}` : `${new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(value)} сум`;
function Input({label,value,onChange,type="text",step,min,max,placeholder,readOnly=false}:{label:string;value:string|number|null;onChange:(value:string)=>void;type?:string;step?:string;min?:number;max?:number;placeholder?:string;readOnly?:boolean}) { return <label className="calculation-field"><span>{label}</span><input type={type} step={step} min={min} max={max} value={value??""} placeholder={placeholder} readOnly={readOnly} onChange={(event)=>onChange(event.target.value)}/></label>; }

export function CalculationProposalSections({draft,setDraft,products,dirty,saving,onSave}:{draft:CalculationDraft;setDraft:Dispatch<SetStateAction<CalculationDraft>>;products:ProductProposalOption[];dirty:boolean;saving:boolean;onSave:()=>Promise<string|null>}) {
  const [preview,setPreview]=useState(false),[pdfBusy,setPdfBusy]=useState<"preview"|"download"|"share"|null>(null),[pdfError,setPdfError]=useState("");
  const set=<K extends keyof CalculationDraft>(key:K,value:CalculationDraft[K])=>setDraft(current=>({...current,[key]:value}));
  const totals=useMemo(()=>quotationTotals(draft.lineItems,draft.discountPercent),[draft.lineItems,draft.discountPercent]);
  const addItem=()=>set("lineItems",[...draft.lineItems,{id:crypto.randomUUID(),productId:null,name:"",unit:"шт",quantity:1,unitPrice:0,currency:"USD",order:draft.lineItems.length}]);
  const updateItem=(id:string,key:string,value:unknown)=>setDraft(current=>({...current,lineItems:current.lineItems.map(item=>item.id===id?{...item,[key]:value}:item)}));
  const pdfUrl=(id=draft.id)=>id?`/admin/calculations/${id}/pdf`:"";
  const ensureSaved=async()=>!draft.id||dirty?onSave():draft.id;
  async function fetchPdf(action:"preview"|"download"|"share") {
    setPdfBusy(action);setPdfError("");
    try {
      const id=await ensureSaved();if(!id)return;
      if(action==="preview"){setPreview(true);return;}
      const response=await fetch(pdfUrl(id));if(!response.ok)throw new Error(await response.text());
      const blob=await response.blob(),file=new File([blob],`${draft.proposalNumber||"commercial-proposal"}.pdf`,{type:"application/pdf"});
      if(action==="share"&&navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:"BUYUK KARAVAN tijorat taklifi",files:[file]});
      else {const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;anchor.click();URL.revokeObjectURL(url);}
    } catch {setPdfError("PDF yaratilmadi. Taklif ma’lumotlarini tekshirib, qayta urinib ko‘ring.");}
    finally {setPdfBusy(null);}
  }
  return <div className="proposal-sections">
    <section className="admin-form-card"><div className="proposal-section-heading"><div><span>05</span><h2>Tijorat taklifi rasmi / 3D render</h2><p>Ixtiyoriy. Faqat Admin tasdiqlagan JPEG, PNG yoki WebP manzilini kiriting.</p></div></div><Input label="Rasm URL" value={draft.renderImageUrl} placeholder="https://.../render.webp" onChange={value=>set("renderImageUrl",value)}/></section>
    <section className="admin-form-card"><div className="proposal-section-heading"><div><span>06</span><h2>Taklifning yakuniy smetasi</h2><p>Mahsulot, material va xizmatlarni qo‘lda yoki katalogdan kiriting.</p></div><button type="button" onClick={addItem}><Plus size={15}/>Qator qo‘shish</button></div>
      <div className="proposal-items">{draft.lineItems.map((item,index)=><article className="proposal-item" key={item.id}><b>{index+1}</b><label><span>Mavjud mahsulot</span><select value={item.productId||""} onChange={event=>{const product=products.find(value=>value.id===event.target.value);updateItem(item.id,"productId",product?.id||null);if(product){updateItem(item.id,"name",product.model&&!product.name.toLowerCase().includes(product.model.toLowerCase())?`${product.name} ${product.model}`:product.name);if(product.priceUsd)updateItem(item.id,"unitPrice",Number(product.priceUsd));}}}><option value="">Qo‘lda kiritish</option>{products.map(product=><option value={product.id} key={product.id}>{product.name} — {product.model}</option>)}</select></label><Input label="Mahsulot / xizmat" value={item.name} onChange={value=>updateItem(item.id,"name",value)}/><Input label="Birlik" value={item.unit} onChange={value=>updateItem(item.id,"unit",value)}/><Input label="Miqdor" type="number" step="0.001" min={0.001} value={item.quantity} onChange={value=>updateItem(item.id,"quantity",num(value)??0)}/><Input label="Birlik narxi" type="number" step="0.01" min={0} value={item.unitPrice} onChange={value=>updateItem(item.id,"unitPrice",num(value)??0)}/><label><span>Valyuta</span><select value={item.currency} onChange={event=>updateItem(item.id,"currency",event.target.value)}><option>USD</option><option>UZS</option></select></label><strong>{money(quotationTotals([item],0)[item.currency==="USD"?"usdTotal":"uzsTotal"],item.currency)}</strong><button type="button" aria-label="Qatorni o‘chirish" onClick={()=>set("lineItems",draft.lineItems.filter(value=>value.id!==item.id).map((value,order)=>({...value,order})))}><Trash2 size={15}/></button></article>)}</div>
      <div className="proposal-totals"><Input label="Chegirma (%)" type="number" step="0.01" min={0} max={100} value={draft.discountPercent} onChange={value=>set("discountPercent",num(value))}/><dl><div><dt>USD subtotal</dt><dd>{money(totals.usdSubtotal,"USD")}</dd></div><div><dt>Chegirma</dt><dd>−{money(totals.usdDiscount,"USD")}</dd></div><div><dt>Всего: без НДС</dt><dd>{money(totals.usdTotal,"USD")}</dd></div>{totals.uzsTotal>0&&<div><dt>JAMI UZS</dt><dd>{money(totals.uzsTotal)}</dd></div>}</dl></div>
    </section>
    <section className="admin-form-card"><div className="proposal-section-heading"><div><span>07</span><h2>Yakuniy summa va izoh</h2></div></div><div className="proposal-fields"><Input label="Перечисления с учётом НДС (UZS)" type="number" step="1" min={0} value={draft.manualUzsTotalWithVat} onChange={value=>set("manualUzsTotalWithVat",num(value))}/><Input label="Taklif raqami" value={draft.proposalNumber} placeholder="Saqlanganda avtomatik yaratiladi" readOnly onChange={()=>{}}/><Input label="Taklif sanasi" type="date" value={draft.proposalDate} onChange={value=>set("proposalDate",value)}/><Input label="Amal qilish muddati (kun)" type="number" min={1} max={365} value={draft.validityDays} onChange={value=>set("validityDays",num(value))}/><label className="calculation-field is-wide"><span>PS. Izoh</span><textarea rows={4} value={draft.proposalNote} onChange={event=>set("proposalNote",event.target.value)}/></label></div></section>
    <section className="admin-form-card proposal-pdf" id="proposal-pdf-section"><div className="proposal-section-heading"><div><span>08</span><h2>PDF ko‘rish va ulashish</h2><p>PDF saqlangan va serverda tekshirilgan ma’lumotlardan yaratiladi.</p></div></div><div className="proposal-pdf-actions"><button type="button" disabled={pdfBusy!==null||saving} onClick={()=>void fetchPdf("preview")}><Eye size={16}/>{pdfBusy==="preview"?"Tayyorlanmoqda...":!draft.id||dirty?"Saqlash va PDF ko‘rish":"PDF ko‘rish"}</button>{draft.id&&<button type="button" disabled={pdfBusy!==null||saving} onClick={()=>void fetchPdf("download")}><Download size={16}/>{pdfBusy==="download"?"Tayyorlanmoqda...":"PDF yuklab olish"}</button>}{draft.id&&<button type="button" disabled={pdfBusy!==null||saving} onClick={()=>void fetchPdf("share")}><Share2 size={16}/>{pdfBusy==="share"?"Tayyorlanmoqda...":"Ulashish"}</button>}</div>{pdfError&&<p className="proposal-pdf-error" role="alert">{pdfError}</p>}{preview&&<iframe title="Tijorat taklifi PDF ko‘rinishi" src={`${pdfUrl()}?inline=1`}/>}</section>
  </div>;
}
