"use client";

import { useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import type { FeaturedProductRef, HomeContent, HomeSectionKey, ManagedItem, ManagedProject, ManagedReason } from "@/data/admin-home";
import { AdminImageField, HomeTextField, OrderControls, VisibilityToggle } from "./home-controls";

const newId = () => `draft-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function moveItem<T extends { order: number }>(items: T[], index: number, direction: -1 | 1): T[] {
  const target=index+direction;if(target<0||target>=items.length)return items;
  const next=[...items];[next[index],next[target]]=[next[target],next[index]];
  return next.map((item,position)=>({...item,order:position+1}));
}
function ItemEditor({ item, onChange, onDelete, index, count, onMove, kind }: { item: ManagedItem; onChange: (item: ManagedItem)=>void; onDelete:()=>void; index:number; count:number; onMove:(direction:-1|1)=>void; kind:"selector"|"solution" }) {
  const [expanded,setExpanded]=useState(false);
  return <div className="home-managed-item"><div className="home-managed-item-head"><span className="home-item-order">{String(index+1).padStart(2,"0")}</span><strong>{item.title||"Yangi variant"}</strong><VisibilityToggle visible={item.isVisible} onChange={isVisible=>onChange({...item,isVisible})}/><OrderControls index={index} count={count} onMove={onMove}/><button className="home-icon-action" type="button" aria-label="Tahrirlash" onClick={()=>setExpanded(!expanded)}><Pencil size={15}/></button><button className="home-icon-action is-danger" type="button" aria-label="O‘chirish" onClick={onDelete}><Trash2 size={15}/></button></div>
    {expanded&&<div className="home-managed-item-fields"><HomeTextField label="Nomi" value={item.title} onChange={title=>onChange({...item,title})}/><HomeTextField label="Ikonka belgisi" value={item.icon} onChange={icon=>onChange({...item,icon})}/>{kind==="solution"&&<><HomeTextField label="Qisqa tavsif" value={item.description} multiline onChange={description=>onChange({...item,description})}/><AdminImageField label="Yechim rasmi" ratio="16:9" value={item.image} onChange={image=>onChange({...item,image})}/></>}</div>}
  </div>;
}
function ManagedItemsEditor({ items, onChange, kind }: { items: ManagedItem[]; onChange:(items:ManagedItem[])=>void; kind:"selector"|"solution" }) {
  const update=(id:string,next:ManagedItem)=>onChange(items.map(item=>item.id===id?next:item));
  return <><div className="home-editor-list">{items.map((item,index)=><ItemEditor key={item.id} item={item} kind={kind} index={index} count={items.length} onChange={next=>update(item.id,next)} onDelete={()=>onChange(items.filter(entry=>entry.id!==item.id).map((entry,position)=>({...entry,order:position+1})))} onMove={direction=>onChange(moveItem(items,index,direction))}/>)}</div><button className="home-add-button" type="button" onClick={()=>onChange([...items,{id:newId(),title:"",description:"",icon:"",image:null,isVisible:true,order:items.length+1}])}><Plus size={16}/>{kind==="selector"?"Variant qo‘shish":"Yechim qo‘shish"}</button></>;
}
function ProjectRow({ item, index, count, onChange, onDelete, onMove }: { item:ManagedProject; index:number; count:number; onChange:(item:ManagedProject)=>void; onDelete:()=>void; onMove:(direction:-1|1)=>void }) {
  const [expanded,setExpanded]=useState(false);
  return <div className="home-managed-item"><div className="home-managed-item-head"><span className="home-item-order">{String(index+1).padStart(2,"0")}</span><strong>{item.title||"Yangi loyiha"}</strong><VisibilityToggle visible={item.isVisible} onChange={isVisible=>onChange({...item,isVisible})}/><OrderControls index={index} count={count} onMove={onMove}/><button className="home-icon-action" type="button" aria-label="Tahrirlash" onClick={()=>setExpanded(!expanded)}><Pencil size={15}/></button><button className="home-icon-action is-danger" type="button" aria-label="O‘chirish" onClick={onDelete}><Trash2 size={15}/></button></div>
    {expanded&&<div className="home-managed-item-fields"><HomeTextField label="Loyiha nomi" value={item.title} onChange={title=>onChange({...item,title})}/><HomeTextField label="Kategoriya" value={item.category} onChange={category=>onChange({...item,category})}/><HomeTextField label="Harorat" value={item.temperature} onChange={temperature=>onChange({...item,temperature})}/><HomeTextField label="Joylashuv (ixtiyoriy)" value={item.location} onChange={location=>onChange({...item,location})}/><HomeTextField label="Qisqa tavsif" value={item.description} multiline onChange={description=>onChange({...item,description})}/><AdminImageField label="Loyiha rasmi" ratio="4:3" value={item.image} onChange={image=>onChange({...item,image})}/></div>}
  </div>;
}
function ProjectsEditor({ items, onChange }: { items:ManagedProject[]; onChange:(items:ManagedProject[])=>void }) {
  return <><div className="home-editor-list">{items.map((item,index)=><ProjectRow key={item.id} item={item} index={index} count={items.length} onChange={next=>onChange(items.map(entry=>entry.id===item.id?next:entry))} onDelete={()=>onChange(items.filter(entry=>entry.id!==item.id).map((entry,position)=>({...entry,order:position+1})))} onMove={direction=>onChange(moveItem(items,index,direction))}/>)}</div><button className="home-add-button" type="button" onClick={()=>onChange([...items,{id:newId(),title:"",category:"",temperature:"",description:"",location:"",image:null,isVisible:true,order:items.length+1}])}><Plus size={16}/>Yangi loyiha</button></>;
}
function ReasonRow({ item, index, count, onChange, onDelete, onMove }: { item:ManagedReason; index:number; count:number; onChange:(item:ManagedReason)=>void; onDelete:()=>void; onMove:(direction:-1|1)=>void }) {
  const [expanded,setExpanded]=useState(false);
  return <div className="home-managed-item"><div className="home-managed-item-head"><span className="home-item-order">{String(index+1).padStart(2,"0")}</span><strong>{item.title||"Yangi sabab"}</strong><VisibilityToggle visible={item.isVisible} onChange={isVisible=>onChange({...item,isVisible})}/><OrderControls index={index} count={count} onMove={onMove}/><button className="home-icon-action" type="button" aria-label="Tahrirlash" onClick={()=>setExpanded(!expanded)}><Pencil size={15}/></button><button className="home-icon-action is-danger" type="button" aria-label="O‘chirish" onClick={onDelete}><Trash2 size={15}/></button></div>{expanded&&<div className="home-managed-item-fields"><HomeTextField label="Sarlavha" value={item.title} onChange={title=>onChange({...item,title})}/><HomeTextField label="Tavsif" value={item.description} multiline onChange={description=>onChange({...item,description})}/></div>}</div>;
}
function ReasonsEditor({ items, onChange }: { items:ManagedReason[]; onChange:(items:ManagedReason[])=>void }) {
  return <><div className="home-editor-list">{items.map((item,index)=><ReasonRow key={item.id} item={item} index={index} count={items.length} onChange={next=>onChange(items.map(entry=>entry.id===item.id?next:entry))} onDelete={()=>onChange(items.filter(entry=>entry.id!==item.id).map((entry,position)=>({...entry,order:position+1})))} onMove={direction=>onChange(moveItem(items,index,direction))}/>)}</div><button className="home-add-button" type="button" onClick={()=>onChange([...items,{id:newId(),title:"",description:"",isVisible:true,order:items.length+1}])}><Plus size={16}/>Sabab qo‘shish</button></>;
}
type ProductOption = { id:string; name:string; model:string };
function FeaturedProductsEditor({ items, products, onChange }: { items:FeaturedProductRef[]; products:ProductOption[]; onChange:(items:FeaturedProductRef[])=>void }) {
  const [showPicker,setShowPicker]=useState(false);
  return <><div className="home-editor-list">{items.map((item,index)=>{const product=products.find(entry=>entry.id===item.productId);if(!product)return null;return <div className="home-managed-item-head" key={item.productId}><span className="home-item-order">{String(index+1).padStart(2,"0")}</span><strong>{product.name} <small>{product.model}</small></strong><VisibilityToggle visible={item.isVisible} onChange={isVisible=>onChange(items.map(entry=>entry.productId===item.productId?{...entry,isVisible}:entry))}/><OrderControls index={index} count={items.length} onMove={direction=>onChange(moveItem(items,index,direction))}/><button className="home-icon-action is-danger" type="button" aria-label="Ro‘yxatdan olish" onClick={()=>onChange(items.filter(entry=>entry.productId!==item.productId).map((entry,position)=>({...entry,order:position+1})))}><Trash2 size={15}/></button></div>;})}</div><button className="home-add-button" type="button" onClick={()=>setShowPicker(!showPicker)}><Plus size={16}/>Ko‘rsatiladigan mahsulotlarni tanlash</button>{showPicker&&<div className="home-product-picker">{products.map(product=><label key={product.id}><input type="checkbox" checked={items.some(item=>item.productId===product.id)} onChange={event=>onChange(event.target.checked?[...items,{productId:product.id,isVisible:true,order:items.length+1}]:items.filter(item=>item.productId!==product.id).map((item,index)=>({...item,order:index+1})))}/><span>{product.name} <small>{product.model}</small></span></label>)}</div>}</>;
}
export function HomeSectionEditor({ section, content, products, onChange }: { section:HomeSectionKey; content:HomeContent; products:ProductOption[]; onChange:<K extends HomeSectionKey>(key:K,value:HomeContent[K])=>void }) {
  switch(section){
    case "hero": {const value=content.hero;const update=(patch:Partial<typeof value>)=>onChange("hero",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Headline" value={value.headline} multiline onChange={headline=>update({headline})}/><HomeTextField label="Subtitle" value={value.subtitle} multiline onChange={subtitle=>update({subtitle})}/><div className="home-editor-two"><HomeTextField label="Asosiy tugma" value={value.primaryButton} onChange={primaryButton=>update({primaryButton})}/><HomeTextField label="Ikkinchi tugma" value={value.secondaryButton} onChange={secondaryButton=>update({secondaryButton})}/></div><div className="home-editor-two"><HomeTextField label="Minimum harorat" value={value.minimum} onChange={minimum=>update({minimum})}/><HomeTextField label="Maksimum harorat" value={value.maximum} onChange={maximum=>update({maximum})}/></div><AdminImageField label="Hero fon rasmi" ratio="16:9" value={value.image} onChange={image=>update({image})}/><p className="home-editor-hint">Animatsiyadagi kontur va yorug‘lik yo‘li kodda boshqariladi; bu yerda faqat kontent o‘zgaradi.</p></div>;}
    case "selector": {const value=content.selector;const update=(patch:Partial<typeof value>)=>onChange("selector",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Sarlavha" value={value.title} onChange={title=>update({title})}/><HomeTextField label="Tavsif" value={value.description} multiline onChange={description=>update({description})}/><h3>Tanlov variantlari</h3><ManagedItemsEditor items={value.items} kind="selector" onChange={items=>update({items})}/></div>;}
    case "solutions": {const value=content.solutions;const update=(patch:Partial<typeof value>)=>onChange("solutions",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Sarlavha" value={value.title} onChange={title=>update({title})}/><h3>Yechimlar</h3><ManagedItemsEditor items={value.items} kind="solution" onChange={items=>update({items})}/></div>;}
    case "featuredProducts": {const value=content.featuredProducts;const update=(patch:Partial<typeof value>)=>onChange("featuredProducts",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Sarlavha" value={value.title} onChange={title=>update({title})}/><HomeTextField label="Tavsif" value={value.description} multiline onChange={description=>update({description})}/><h3>Tanlangan mahsulotlar</h3><FeaturedProductsEditor items={value.items} products={products} onChange={items=>update({items})}/></div>;}
    case "temperature": {const value=content.temperature;const update=(patch:Partial<typeof value>)=>onChange("temperature",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Sarlavha" value={value.title} onChange={title=>update({title})}/><HomeTextField label="Tavsif" value={value.description} multiline onChange={description=>update({description})}/><div className="home-editor-two"><HomeTextField label="Minimum harorat" value={value.minimum} onChange={minimum=>update({minimum})}/><HomeTextField label="Maksimum harorat" value={value.maximum} onChange={maximum=>update({maximum})}/></div><HomeTextField label="Qo‘shimcha yorliqlar" value={value.labels} multiline onChange={labels=>update({labels})}/><p className="home-editor-hint">Harorat animatsiyasi kodda boshqariladi.</p></div>;}
    case "projects": {const value=content.projects;const update=(patch:Partial<typeof value>)=>onChange("projects",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Sarlavha" value={value.title} onChange={title=>update({title})}/><h3>Loyihalar</h3><ProjectsEditor items={value.items} onChange={items=>update({items})}/></div>;}
    case "reasons": {const value=content.reasons;const update=(patch:Partial<typeof value>)=>onChange("reasons",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Eyebrow" value={value.eyebrow} onChange={eyebrow=>update({eyebrow})}/><HomeTextField label="Asosiy sarlavha" value={value.headline} multiline onChange={headline=>update({headline})}/><h3>Sabablar</h3><ReasonsEditor items={value.items} onChange={items=>update({items})}/></div>;}
    case "cta": {const value=content.cta;const update=(patch:Partial<typeof value>)=>onChange("cta",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Sarlavha" value={value.headline} multiline onChange={headline=>update({headline})}/><HomeTextField label="Tavsif" value={value.description} multiline onChange={description=>update({description})}/><HomeTextField label="Asosiy tugma" value={value.primaryButton} onChange={primaryButton=>update({primaryButton})}/><HomeTextField label="Ikkinchi tugma" value={value.secondaryButton} onChange={secondaryButton=>update({secondaryButton})}/></div>;}
    case "footer": {const value=content.footer;const update=(patch:Partial<typeof value>)=>onChange("footer",{...value,...patch});return <div className="home-editor-fields"><HomeTextField label="Kompaniya tavsifi" value={value.companyDescription} multiline onChange={companyDescription=>update({companyDescription})}/><HomeTextField label="Joylashuv" value={value.location} onChange={location=>update({location})}/><HomeTextField label="Telefon" value={value.phone} onChange={phone=>update({phone})}/><HomeTextField label="Telegram username" value={value.telegram} onChange={telegram=>update({telegram})}/><HomeTextField label="Instagram username" value={value.instagram} onChange={instagram=>update({instagram})}/><p className="home-editor-hint">Navigatsiya manzillari dasturda boshqariladi va bu yerda o‘zgartirilmaydi.</p></div>;}
  }
}
