/* eslint-disable react/no-unescaped-entities */
"use client";
import { useEffect,useRef,useState,useTransition } from "react";
import Link from "next/link";
import { ProductImageUploader,type ProductImagePreview } from "./product-image-uploader";
import { saveProjectAction } from "@/app/admin/(protected)/projects/actions";
import type { Project } from "@/lib/projects/types";
const slugify=(s:string)=>s.toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const empty={title:"",slug:"",shortDescription:"",description:"",location:"",temperature:"",capacity:"",category:"",isVisible:true,isFeatured:false,order:0};
export function ProjectForm({project}:{project?:Project}){const [state,setState]=useState(project?{title:project.title,slug:project.slug,shortDescription:project.shortDescription,description:project.description,location:project.location,temperature:project.temperature,capacity:project.capacity,category:project.category,isVisible:project.isVisible,isFeatured:project.isFeatured,order:project.order}:empty);const [images,setImages]=useState<ProductImagePreview[]>(()=>(project?.images||[]).map((url,i)=>({id:`old-${i}`,url,name:`${i+1}-rasm`})));const [edited,setEdited]=useState(Boolean(project)),[feedback,setFeedback]=useState(""),[pending,start]=useTransition();const urls=useRef<string[]>([]);useEffect(()=>{urls.current=images.filter(x=>x.file).map(x=>x.url)},[images]);useEffect(()=>()=>urls.current.forEach(URL.revokeObjectURL),[]);const update=(key:keyof typeof state,value:string|number|boolean)=>setState(s=>({...s,[key]:value}));const save=()=>start(async()=>{if(!images.length){setFeedback("Kamida bitta rasm kiriting.");return;}const result=await saveProjectAction(project?.id||null,state,images.map(x=>x.file?{file:x.file}:{url:x.url}));if(result?.error)setFeedback(result.error)});return <div className="admin-form-page"><div className="admin-page-heading"><div><Link className="admin-back-link" href="/admin/projects">← Loyihalarga qaytish</Link><h1>{project?"Loyihani tahrirlash":"Yangi loyiha"}</h1><p>Saytda ko'rsatiladigan real loyiha ma'lumotlari</p></div></div><div className="admin-form-layout"><div className="admin-form-main"><section className="admin-form-card"><div className="admin-form-card-heading"><h2>Asosiy ma'lumotlar</h2></div><div className="admin-form-grid">
{[["title","Loyiha nomi"],["slug","Slug"],["category","Kategoriya"],["location","Manzil"],["temperature","Harorat"],["capacity","Quvvat / sig'im"]].map(([key,label])=><label className="admin-form-field" key={key}><span>{label}</span><input value={String(state[key as keyof typeof state])} onChange={e=>{const v=e.target.value;update(key as keyof typeof state,v);if(key==="title"&&!edited)update("slug",slugify(v));if(key==="slug")setEdited(true)}}/></label>)}
<label className="admin-form-field"><span>Qisqa tavsif</span><textarea rows={3} value={state.shortDescription} onChange={e=>update("shortDescription",e.target.value)}/></label><label className="admin-form-field"><span>To'liq tavsif</span><textarea rows={7} value={state.description} onChange={e=>update("description",e.target.value)}/></label></div></section><ProductImageUploader images={images} onChange={setImages} onError={setFeedback}/></div><aside className="admin-form-side"><section className="admin-form-card"><h2>Ko'rinish</h2><label className="admin-form-switch"><input type="checkbox" checked={state.isVisible} onChange={e=>update("isVisible",e.target.checked)}/><span>Saytda ko'rsatish</span></label><label className="admin-form-switch"><input type="checkbox" checked={state.isFeatured} onChange={e=>update("isFeatured",e.target.checked)}/><span>Tanlangan loyiha</span></label></section><section className="admin-form-card"><label className="admin-form-field"><span>Tartib</span><input type="number" min={0} value={state.order} onChange={e=>update("order",Number(e.target.value))}/></label></section></aside></div>{feedback&&<p className="admin-form-feedback" role="status">{feedback}</p>}<div className="admin-save-bar"><Link href="/admin/projects">Bekor qilish</Link><button className="admin-primary-button" disabled={pending} onClick={save}>{pending?"Saqlanmoqda...":"Loyihani saqlash"}</button></div></div>}
