"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { Check, CheckCircle2, ChevronDown, Download, Expand, ImageIcon, Layers3, PackageCheck, RefreshCw, ScanLine, ShieldCheck, Sparkles, Trash2, UploadCloud, X } from "lucide-react";
import { processPhotoStudioImageAction, saveApprovedPhotoStudioImageAction } from "@/app/admin/(protected)/photo-studio/actions";
import { PhotoStudioGenerationProgress } from "./photo-studio-generation-progress";
import { getPhotoStudioModeConfig, photoStudioModeConfigs } from "@/lib/photo-studio/modes";
import { photoStudioModes, type PhotoStudioAdvertisingData, type PhotoStudioAspectRatio, type PhotoStudioBackground, type PhotoStudioMode, type PhotoStudioResult, type PhotoStudioSettings } from "@/lib/photo-studio/types";

type StudioFile = { file: File; url: string };
type Phase = "idle" | "processing" | "success" | "error" | "result";
type ProductOption = { id: string; name: string; model: string };
type AdvertisingForm = Omit<PhotoStudioAdvertisingData, "benefits" | "applications"> & { benefits: string; applications: string };
const defaultAdvertising: AdvertisingForm = { command: "/creativeads", brand: "", headline: "", subheadline: "", benefits: "", applications: "", phone: "", website: "", cta: "" };

function FilePicker({ value, onChange, onError }: { value?: StudioFile; onChange: (file?: StudioFile) => void; onError: (message: string) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const pick = (file?: File) => {
    if (!file) return;
    if (!["image/png", "image/jpeg", "image/webp"].includes(file.type)) return onError("Rasm formati qo‘llab-quvvatlanmaydi. PNG, JPG yoki WebP yuklang.");
    if (file.size > 10 * 1024 * 1024) return onError("Rasm hajmi juda katta. Maksimal hajm 10 MB.");
    onError("");
    onChange({ file, url: URL.createObjectURL(file) });
  };
  if (value) return <div className="studio-file">
    <Image unoptimized src={value.url} alt={value.file.name} width={320} height={200}/><span className="studio-file-check"><Check size={13}/></span>
    <div className="studio-file-meta"><strong>{value.file.name}</strong><small>{Math.max(1, Math.round(value.file.size / 1024))} KB</small></div>
    <div className="studio-file-actions"><button type="button" onClick={() => input.current?.click()}>Almashtirish</button><button type="button" aria-label="Rasmni olib tashlash" onClick={() => onChange()}><Trash2 size={14}/></button></div>
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event => { pick(event.target.files?.[0]); event.target.value = ""; }}/>
  </div>;
  return <div className="studio-drop" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); pick(event.dataTransfer.files[0]); }}>
    <UploadCloud size={28}/><span>Rasmni shu yerga tashlang</span><button type="button" onClick={() => input.current?.click()}>Rasm tanlash</button><small>PNG, JPG, WebP · 10 MB gacha</small>
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event => { pick(event.target.files?.[0]); event.target.value = ""; }}/>
  </div>;
}

function Toggle({ label, checked, onChange, locked = false }: { label: string; checked: boolean; onChange: () => void; locked?: boolean }) {
  return <button type="button" className="studio-toggle-row" onClick={onChange} disabled={locked}><span>{label}{locked && <small>Majburiy</small>}</span><i className={checked ? "is-on" : ""}/></button>;
}

function Choice<T extends string | number>({ value, options, onChange }: { value: T; options: readonly { value: T; label: string }[]; onChange: (value: T) => void }) {
  return <div className="studio-choice-grid">{options.map(option => <button type="button" key={option.value} className={value === option.value ? "is-active" : ""} onClick={() => onChange(option.value)}>{option.label}</button>)}</div>;
}

function Protection({ settings, update, environment = false }: { settings: PhotoStudioSettings; update: <K extends keyof PhotoStudioSettings>(key: K, value: PhotoStudioSettings[K]) => void; environment?: boolean }) {
  const [open, setOpen] = useState(false);
  return <div className="studio-protection"><div><span><ShieldCheck size={17}/>{environment ? "REAL MUHITNI SAQLASH" : "MAHSULOTNI HIMOYA QILISH"}</span><button type="button" onClick={() => !environment && update("protectProduct", !settings.protectProduct)} aria-label="Himoya sozlamasi"><i className={(environment || settings.protectProduct) ? "is-on" : ""}/></button></div><p>{environment ? "Real uskuna, xona va montaj muhiti o‘zgartirilmaydi." : "Texnik tuzilish badiiy ijodkorlikdan ustun turadi."}</p><button type="button" className="studio-checklist-toggle" onClick={() => setOpen(!open)}>Himoya elementlari <ChevronDown className={open ? "is-open" : ""} size={15}/></button>{open && <ul>{(environment ? ["Xona va bino", "Quvurlar", "Montaj", "Uskunalar", "Fazoviy nisbat", "Texnik qismlar"] : ["Logo va model", "Fanlar soni", "Quvurlar", "Korpus geometriyasi", "Ulanishlar", "Texnik qismlar"]).map(item => <li key={item}><Check size={13}/>{item}</li>)}</ul>}</div>;
}

function SettingsPanel({ mode, settings, advertising, ready, phase, onSettings, onAdvertising, onGenerate }: { mode: PhotoStudioMode; settings: PhotoStudioSettings; advertising: AdvertisingForm; ready: boolean; phase: Phase; onSettings: (next: PhotoStudioSettings) => void; onAdvertising: (next: AdvertisingForm) => void; onGenerate: () => void }) {
  const update = <K extends keyof PhotoStudioSettings>(key: K, value: PhotoStudioSettings[K]) => onSettings({ ...settings, [key]: value });
  const sizes = [1000, 1500, 2000] as const;
  return <section className="studio-card studio-controls"><div className="studio-section-title"><div><span>02</span><h2>Sozlamalar</h2></div></div>
    {mode === "card" && <><label>FON</label><Choice value={settings.background} options={[{ value: "white", label: "Oq" }, { value: "light-gray", label: "Juda och kulrang" }] as { value: PhotoStudioBackground; label: string }[]} onChange={value => update("background", value)}/><label>O‘LCHAM</label><Choice value={settings.size} options={sizes.map(value => ({ value, label: `${value} × ${value}` }))} onChange={value => update("size", value)}/><div className="studio-toggles"><Toggle label="Fonni tozalash" checked={settings.removeBackground} onChange={() => update("removeBackground", !settings.removeBackground)}/><Toggle label="Rasm sifatini yaxshilash" checked={settings.enhanceQuality} onChange={() => update("enhanceQuality", !settings.enhanceQuality)}/><Toggle label="Ranglarni to‘g‘rilash" checked={settings.correctColors} onChange={() => update("correctColors", !settings.correctColors)}/><Toggle label="Soya va yorug‘lik" checked={settings.improveLighting} onChange={() => update("improveLighting", !settings.improveLighting)}/></div><Protection settings={settings} update={update}/></>}
    {mode === "detail" && <><label>FON MUHITI</label><Choice value={settings.background} options={[{ value: "premium-neutral", label: "Premium neytral" }, { value: "premium-industrial", label: "Industrial studio" }] as { value: PhotoStudioBackground; label: string }[]} onChange={value => update("background", value)}/><label>O‘LCHAM</label><Choice value={settings.size} options={sizes.map(value => ({ value, label: `${value} × ${value}` }))} onChange={value => update("size", value)}/><div className="studio-toggles"><Toggle label="Premium yoritish" checked={settings.premiumLighting} onChange={() => update("premiumLighting", !settings.premiumLighting)}/><Toggle label="Detallarni yaxshilash" checked={settings.detailEnhancement} onChange={() => update("detailEnhancement", !settings.detailEnhancement)}/><Toggle label="Tabiiy soya" checked={settings.naturalShadow} onChange={() => update("naturalShadow", !settings.naturalShadow)}/></div><Protection settings={settings} update={update}/></>}
    {mode === "project" && <><label>O‘LCHAM</label><Choice value={settings.size} options={sizes.map(value => ({ value, label: String(value) }))} onChange={value => update("size", value)}/><label>NISBAT</label><Choice value={settings.aspectRatio} options={[{ value: "original", label: "Original" }, { value: "1:1", label: "1:1" }, { value: "4:5", label: "4:5" }, { value: "16:9", label: "16:9" }] as { value: PhotoStudioAspectRatio; label: string }[]} onChange={value => update("aspectRatio", value)}/><div className="studio-toggles"><Toggle label="Ekspozitsiya" checked={settings.exposure} onChange={() => update("exposure", !settings.exposure)}/><Toggle label="Oq balans" checked={settings.whiteBalance} onChange={() => update("whiteBalance", !settings.whiteBalance)}/><Toggle label="Perspektivani tuzatish" checked={settings.perspectiveCorrection} onChange={() => update("perspectiveCorrection", !settings.perspectiveCorrection)}/><Toggle label="Mayda ortiqcha buyumlarni tozalash" checked={settings.clutterCleanup} onChange={() => update("clutterCleanup", !settings.clutterCleanup)}/><Toggle label="Detallarni yaxshilash" checked={settings.detailEnhancement} onChange={() => update("detailEnhancement", !settings.detailEnhancement)}/><Toggle label="Muhitni saqlash" checked locked onChange={() => undefined}/></div><Protection settings={settings} update={update} environment/></>}
    {mode === "transparent" && <><div className="studio-output-note"><strong>SHAFFOF PNG</strong><span>PNG · haqiqiy alpha shaffofligi</span></div><label>O‘LCHAM</label><Choice value={settings.size} options={sizes.map(value => ({ value, label: `${value} × ${value}` }))} onChange={value => update("size", value)}/><div className="studio-toggles"><Toggle label="Yuqori sifatli qirralar" checked={settings.edgeQuality} onChange={() => update("edgeQuality", !settings.edgeQuality)}/><Toggle label="Nozik detallarni saqlash" checked={settings.fineDetailProtection} onChange={() => update("fineDetailProtection", !settings.fineDetailProtection)}/></div><Protection settings={settings} update={update}/></>}
    {mode === "ad" && <><label>/ KOMANDA</label><div className="studio-command"><button type="button" className="is-active">/creativeads</button><small>Professional 9:16 Reels va Stories reklama kreativi</small></div><div className="studio-toggles"><Toggle label="Premium yoritish" checked={settings.premiumLighting} onChange={() => update("premiumLighting", !settings.premiumLighting)}/></div><Protection settings={settings} update={update}/><details className="studio-ad-fields"><summary>REKLAMA MA’LUMOTLARI <ChevronDown size={15}/></summary><div><label>Brend nomi<input value={advertising.brand} maxLength={100} placeholder="IMPERIAL COOL" onChange={event => onAdvertising({ ...advertising, brand: event.target.value })}/></label><label>Asosiy sarlavha<input value={advertising.headline} maxLength={180} placeholder="Barqaror sovutish — ishonchli tanlov" onChange={event => onAdvertising({ ...advertising, headline: event.target.value })}/></label><label>Qo‘shimcha sarlavha<input value={advertising.subheadline} maxLength={240} placeholder="Sanoat sovutish tizimlari uchun professional yechim" onChange={event => onAdvertising({ ...advertising, subheadline: event.target.value })}/></label><label>Afzalliklar<textarea value={advertising.benefits} maxLength={600} rows={4} placeholder={"Yuqori sovutish samaradorligi\nUzoq muddatli xizmat\nSanoat uchun mo‘ljallangan"} onChange={event => onAdvertising({ ...advertising, benefits: event.target.value })}/></label><label>Qo‘llanish sohasi<textarea value={advertising.applications} maxLength={600} rows={4} placeholder={"Meva-sabzavot\nGo‘sht\nMuzqaymoq\nSanoat loyihalari"} onChange={event => onAdvertising({ ...advertising, applications: event.target.value })}/></label><label>Telefon raqami<input value={advertising.phone} maxLength={80} placeholder="+998 90 123 45 67" onChange={event => onAdvertising({ ...advertising, phone: event.target.value })}/></label><label>Sayt / ijtimoiy tarmoq<input value={advertising.website} maxLength={120} placeholder="buyukkaravan.uz" onChange={event => onAdvertising({ ...advertising, website: event.target.value })}/></label><label>Harakatga chaqiruv<input value={advertising.cta} maxLength={80} placeholder="Bog‘lanish" onChange={event => onAdvertising({ ...advertising, cta: event.target.value })}/></label><p>Faqat tasdiqlangan haqiqiy ma’lumotlarni kiriting. Misollar avtomatik qo‘llanmaydi. Matn rasmga aniq ko‘rinishda server tomonidan qo‘shiladi.</p></div></details></>}
    <button className="studio-generate" disabled={!ready || phase === "processing" || phase === "success"} onClick={onGenerate}>{phase === "processing" || phase === "success" ? <><RefreshCw className="is-spinning" size={17}/>Tayyorlanmoqda...</> : <><Sparkles size={17}/>AI bilan tayyorlash</>}</button>
  </section>;
}

function Preview({ mode, phase, source, result, error, onRetry, compare, setCompare }: { mode: PhotoStudioMode; phase: Phase; source?: StudioFile; result?: PhotoStudioResult; error: string; onRetry: () => void; compare: "original" | "result"; setCompare: (value: "original" | "result") => void }) {
  const config = getPhotoStudioModeConfig(mode);
  if (source && (phase === "processing" || phase === "success" || phase === "error")) return <section className="studio-card studio-preview"><PhotoStudioGenerationProgress mode={mode} uploadedImageUrl={source.url} isGenerating={phase === "processing"} isSuccess={phase === "success"} error={error} onRetry={onRetry}/></section>;
  if (phase === "result" && result && result.mode === mode) return <section className={`studio-card studio-preview ${mode === "transparent" ? "is-transparent-result" : ""}`}><div className="studio-preview-label"><span>{config.resultLabel}</span><b>{result.width} × {result.height}</b></div><div className="studio-compare-tabs"><button className={compare === "original" ? "is-active" : ""} onClick={() => setCompare("original")}>ORIGINAL</button><button className={compare === "result" ? "is-active" : ""} onClick={() => setCompare("result")}>NATIJA</button></div><div className={`studio-result ${compare === "result" ? "is-result" : ""}`}>{source && <Image unoptimized src={compare === "result" ? `data:${result.contentType};base64,${result.image}` : source.url} alt={compare === "result" ? config.resultLabel : "Original mahsulot rasmi"} width={result.width} height={result.height}/>}</div></section>;
  if (source) return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>ORIGINAL PREVIEW</span><b>YUKLANDI</b></div><div className="studio-result studio-source-preview"><Image unoptimized src={source.url} alt="Yuklangan mahsulot rasmi" width={900} height={700}/></div></section>;
  return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>{config.resultLabel}</span><b>KUTILMOQDA</b></div><div className="studio-empty-preview"><div><ScanLine size={34}/></div><strong>{config.label}</strong><span>{config.description}</span></div></section>;
}

function SnowUnit() { return <div className="studio-unit" aria-label="Sovutish qurilmasi maketi"><div className="studio-unit-top"/><div className="studio-fan"><span/><span/><span/><span/></div><div className="studio-fan second"><span/><span/><span/><span/></div><i/><i/></div>; }

function SaveDialog({ open, image, products, onClose, onSaved }: { open: boolean; image?: string; products: ProductOption[]; onClose: () => void; onSaved: () => void }) {
  const [productId, setProductId] = useState(products[0]?.id ?? ""); const [placement, setPlacement] = useState<"main" | "gallery">("main"); const [search, setSearch] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  if (!open) return null;
  const filtered = products.filter(product => `${product.name} ${product.model}`.toLocaleLowerCase("uz").includes(search.toLocaleLowerCase("uz")));
  const save = async () => { if (!image || !productId || saving) return; setSaving(true); setError(""); const response = await saveApprovedPhotoStudioImageAction({ productId, placement, image }); setSaving(false); if (response.error) return setError(response.error); onSaved(); };
  return <div className="studio-modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className="studio-modal" role="dialog" aria-modal="true" aria-labelledby="save-title"><button className="studio-modal-close" onClick={onClose}><X size={18}/></button><div className="studio-modal-icon"><PackageCheck/></div><h2 id="save-title">Mahsulotga biriktirish</h2><p>Bu amal tasdiqlangan natijani doimiy xotiraga yuklaydi va tanlangan mahsulotga biriktiradi.</p><div className="studio-save-options"><button className="is-active"><span><Check size={13}/></span>Mahsulotga biriktirish</button></div><div className="studio-product-select"><label>Mahsulot</label><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Mahsulotni qidiring"/><select value={productId} onChange={event => setProductId(event.target.value)}><option value="">Mahsulotni tanlang</option>{filtered.map(product => <option key={product.id} value={product.id}>{product.name} · {product.model}</option>)}</select><div><label><input type="radio" name="placement" checked={placement === "main"} onChange={() => setPlacement("main")}/> Asosiy rasm</label><label><input type="radio" name="placement" checked={placement === "gallery"} onChange={() => setPlacement("gallery")}/> Galereyaga qo‘shish</label></div></div>{error && <p className="studio-action-error" role="alert">{error}</p>}<button className="studio-modal-save" disabled={!image || !productId || saving} onClick={save}>{saving ? "Saqlanmoqda..." : "Tasdiqlash va biriktirish"}</button><small>“Yuklab olish” bundan alohida va mahsulot ma’lumotlarini o‘zgartirmaydi.</small></div></div>;
}

const recent = ["XUE YING BR +20PG", "Evaporator DD160", "Bitzer 4TES-9Y", "Carrier AquaSnap 30RA", "Sovutish kamerasi"], recentModes = ["Mahsulot kartasi", "Transparent PNG", "Reklama", "Loyiha", "Mahsulot sahifasi"];

export function PhotoStudioWorkspace({ products }: { products: ProductOption[] }) {
  const [mode, setMode] = useState<PhotoStudioMode>("card");
  const [settings, setSettings] = useState<PhotoStudioSettings>({ ...photoStudioModeConfigs.card.defaults });
  const [source, setSourceState] = useState<StudioFile>(); const [phase, setPhase] = useState<Phase>("idle"); const [compare, setCompare] = useState<"original" | "result">("result"); const [result, setResult] = useState<PhotoStudioResult>(); const [dialog, setDialog] = useState(false); const [toast, setToast] = useState(false); const [feedback, setFeedback] = useState(""); const [generationError, setGenerationError] = useState(""); const [advertising, setAdvertising] = useState<AdvertisingForm>(defaultAdvertising); const timers = useRef<number[]>([]); const requestInFlight = useRef(false);
  useEffect(() => () => { timers.current.forEach(clearTimeout); }, []);
  const clearResult = () => { timers.current.forEach(clearTimeout); timers.current = []; setPhase("idle"); setResult(undefined); setGenerationError(""); setDialog(false); };
  const changeMode = (next: PhotoStudioMode) => { if (next === mode) return; setMode(next); setSettings({ ...getPhotoStudioModeConfig(next).defaults }); setFeedback(""); clearResult(); };
  const changeSettings = (next: PhotoStudioSettings) => { setSettings(next); setFeedback(""); clearResult(); };
  const changeAdvertising = (next: AdvertisingForm) => { setAdvertising(next); setFeedback(""); clearResult(); };
  const changeSource = (next?: StudioFile) => { if (source) URL.revokeObjectURL(source.url); setSourceState(next); setFeedback(""); clearResult(); };
  const generate = async () => {
    if (!source || phase === "processing" || phase === "success" || requestInFlight.current) return;
    requestInFlight.current = true;
    setPhase("processing"); setFeedback(""); setGenerationError(""); setResult(undefined);
    const form = new FormData(); form.set("image", source.file); form.set("mode", mode);
    for (const [key, value] of Object.entries(settings)) form.set(key, String(value));
    if (mode === "ad") { form.set("adCommand", advertising.command); form.set("adBrand", advertising.brand); form.set("adHeadline", advertising.headline); form.set("adSubheadline", advertising.subheadline); form.set("adBenefits", advertising.benefits); form.set("adApplications", advertising.applications); form.set("adPhone", advertising.phone); form.set("adWebsite", advertising.website); form.set("adCta", advertising.cta); }
    try {
      const response = await processPhotoStudioImageAction(form);
      if (response.error || !response.image || !response.contentType || !response.width || !response.height || response.mode !== mode) { setGenerationError(response.error ?? "AI xizmati yaroqli rasm qaytarmadi."); setPhase("error"); return; }
      setResult({ image: response.image, contentType: response.contentType, width: response.width, height: response.height, mode: response.mode }); setCompare("result"); setPhase("success"); timers.current.push(window.setTimeout(() => setPhase("result"), 800));
    } catch { setGenerationError("AI xizmatiga ulanishda xatolik yuz berdi."); setPhase("error"); }
    finally { requestInFlight.current = false; }
  };
  const download = () => {
    if (!result || result.mode !== mode) return setFeedback("Yuklab olish uchun joriy rejimda natija yarating.");
    try { const binary = window.atob(result.image); const bytes = new Uint8Array(binary.length); for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index); const url = URL.createObjectURL(new Blob([bytes], { type: result.contentType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${getPhotoStudioModeConfig(mode).downloadStem}-${Date.now()}.png`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); setFeedback(""); } catch { setFeedback("Natijani yuklab olish imkoni bo‘lmadi."); }
  };
  const saved = () => { setDialog(false); setToast(true); timers.current.push(window.setTimeout(() => setToast(false), 2600)); };
  return <div className="photo-studio-page"><header className="studio-heading"><div><span className="studio-ai-badge"><Sparkles size={12}/>AI CREATIVE WORKSPACE</span><h1>AI Foto Studio</h1><p>Har bir rejim o‘z maqsadi, sozlamalari va natija qoidalariga ega.</p></div><div className="studio-steps"><span className="is-active">1 Yuklash</span><i/><span>2 Tayyorlash</span><i/><span>3 Natija</span></div></header>
    <nav className="studio-modes" aria-label="Studio rejimi">{photoStudioModes.map(id => { const item = getPhotoStudioModeConfig(id); return <button key={id} className={mode === id ? "is-active" : ""} onClick={() => changeMode(id)}>{id === "transparent" ? <Layers3/> : id === "ad" ? <Sparkles/> : <ImageIcon/>}<span>{item.label}</span>{mode === id && <CheckCircle2/>}</button>; })}</nav>
    <div className="studio-mode-summary"><strong>{getPhotoStudioModeConfig(mode).label}</strong><span>{getPhotoStudioModeConfig(mode).description}</span></div>
    <div className="studio-workspace"><section className="studio-card studio-sources"><div className="studio-section-title"><div><span>01</span><h2>Original rasm</h2></div></div><FilePicker value={source} onChange={changeSource} onError={setFeedback}/></section><Preview mode={mode} phase={phase} source={source} result={result} error={generationError} onRetry={generate} compare={compare} setCompare={setCompare}/><SettingsPanel mode={mode} settings={settings} advertising={advertising} ready={Boolean(source)} phase={phase} onSettings={changeSettings} onAdvertising={changeAdvertising} onGenerate={generate}/>{feedback && <p className="studio-action-error" role="alert">{feedback}</p>}{phase === "result" && result?.mode === mode && <div className="studio-result-actions"><button onClick={() => setCompare(compare === "result" ? "original" : "result")}><Expand size={15}/>Original / Natija</button><button className="is-download" onClick={download}><Download size={15}/>Yuklab olish</button><button onClick={generate}><RefreshCw size={15}/>Qayta yaratish</button><button className="is-primary" onClick={() => setDialog(true)}><Check size={15}/>Tasdiqlash / Biriktirish</button></div>}</div>
    <section className="studio-recent"><div><h2>Oxirgi ishlovlar</h2><span>Oldingi natijalar</span></div><div className="studio-recent-grid">{recent.map((name, index) => <article key={name}><div><SnowUnit/></div><span><strong>{name}</strong><small>{recentModes[index]}</small></span><b><Check size={11}/>Tayyor</b></article>)}</div></section>
    <SaveDialog open={dialog} image={result?.image} products={products} onClose={() => setDialog(false)} onSaved={saved}/>{toast && <div className="studio-toast"><CheckCircle2 size={18}/><span><strong>Rasm saqlandi</strong>Tasdiqlangan natija mahsulotga biriktirildi.</span></div>}
  </div>;
}
