"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { Aperture, Check, CheckCircle2, ChevronDown, Expand, ImageIcon, Layers3, Maximize2, PackageCheck, Play, RefreshCw, RotateCcw, ScanLine, ShieldCheck, Sparkles, Trash2, UploadCloud, X } from "lucide-react";

type Mode = "card" | "detail" | "360" | "project" | "transparent" | "ad";
type StudioFile = { file: File; url: string };
type Phase = "idle" | "processing" | "result";
const modes: { id: Mode; label: string }[] = [
  { id: "card", label: "Mahsulot kartasi" }, { id: "detail", label: "Mahsulot sahifasi" },
  { id: "360", label: "360° ko‘rinish" }, { id: "project", label: "Loyiha" },
  { id: "transparent", label: "Transparent PNG" }, { id: "ad", label: "Reklama" },
];
const angleLabels = ["Old tomondan", "O‘ng tomondan", "Orqa tomondan", "Chap tomondan"];

function FilePicker({ value, label, compact, onChange }: { value?: StudioFile; label?: string; compact?: boolean; onChange: (file?: StudioFile) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const pick = (file?: File) => {
    if (!file) return;
    if (!["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024) return;
    onChange({ file, url: URL.createObjectURL(file) });
  };
  if (value) return <div className={`studio-file ${compact ? "is-compact" : ""}`}>
    <Image unoptimized src={value.url} alt={label || value.file.name} width={320} height={200}/>
    <span className="studio-file-check"><Check size={13}/></span>
    <div className="studio-file-meta"><strong>{label || value.file.name}</strong><small>{value.file.name}</small></div>
    <div className="studio-file-actions"><button type="button" onClick={() => input.current?.click()}>Almashtirish</button><button type="button" aria-label="Rasmni olib tashlash" onClick={() => onChange()}><Trash2 size={14}/></button></div>
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { pick(e.target.files?.[0]); e.target.value=""; }}/>
  </div>;
  return <div className={`studio-drop ${compact ? "is-compact" : ""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0]);}}>
    {label && <strong className="studio-angle-label">{label}</strong>}<UploadCloud size={compact ? 20 : 28}/><span>Rasmni shu yerga tashlang</span><button type="button" onClick={()=>input.current?.click()}>Rasm tanlash</button>{!compact && <small>PNG, JPG, WebP · 10 MB gacha</small>}
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{pick(e.target.files?.[0]);e.target.value="";}}/>
  </div>;
}

function SourcePanel({ mode, source, angles, setSource, setAngle }: { mode: Mode; source?: StudioFile; angles: (StudioFile|undefined)[]; setSource:(v?:StudioFile)=>void; setAngle:(i:number,v?:StudioFile)=>void }) {
  const complete=angles.filter(Boolean).length;
  return <section className="studio-card studio-sources"><div className="studio-section-title"><div><span>01</span><h2>Original rasmlar</h2></div>{mode==="360"&&<b>{complete} / 4</b>}</div>
    {mode==="360"?<><p>Mahsulotni 4 tomondan suratga oling.</p>{complete===4&&<div className="studio-ready-note"><CheckCircle2 size={15}/>4 ta rakurs tayyor</div>}<div className="studio-angle-grid">{angleLabels.map((label,i)=><FilePicker key={label} label={label} compact value={angles[i]} onChange={v=>setAngle(i,v)}/>)}</div><div className="studio-helper"><Aperture size={16}/><span>Barcha rasmlarda mahsulot taxminan bir xil masofa va balandlikda bo‘lishi tavsiya etiladi.</span></div><details className="studio-capture-guide"><summary>Qanday suratga olish kerak?<ChevronDown size={15}/></summary><ol><li>Mahsulotni bir joyda qoldiring.</li><li>Kamera balandligini o‘zgartirmang.</li><li>Taxminan bir xil masofadan suratga oling.</li><li>Old → O‘ng → Orqa → Chap tartibida oling.</li><li>Mahsulot to‘liq kadr ichida bo‘lsin.</li></ol></details></>:<FilePicker value={source} onChange={setSource}/>}</section>;
}

function Preview({ mode, phase, source, compare, setCompare }: { mode:Mode; phase:Phase; source?:StudioFile; compare:"original"|"result"; setCompare:(v:"original"|"result")=>void }) {
  if(phase==="processing") return <section className="studio-card studio-preview"><div className="studio-processing"><div className="studio-product-mock"><SnowUnit/></div><span className="studio-scan"/><Sparkles size={24}/><strong>AI mahsulot rasmini tayyorlamoqda...</strong><small>Fon, yorug‘lik va mahsulot aniqligi tekshirilmoqda</small></div></section>;
  if(mode==="360") return <section className="studio-card studio-preview studio-360"><div className="studio-preview-label"><span>360° PREVIEW VIEWER</span><b>DEMO</b></div><div className="studio-viewer-product"><SnowUnit/><div className="studio-orbit"/><strong>360°</strong><span>Mahsulotni aylantirib ko‘rish</span><small>← drag →</small></div><div className="studio-viewer-tools"><button><Play size={14}/>Avtomatik aylantirish</button><button><RotateCcw size={14}/>Boshlang‘ich holat</button><button><Maximize2 size={14}/>To‘liq ekran</button></div><div className="studio-public-concept"><div><span>SAYTDA QANDAY KO‘RINADI?</span><strong>Mahsulot sahifasi vizual tartibi</strong></div><nav><b>1</b><span>360° ko‘rinish<small>Default / birinchi</small></span><b>2</b><span>Rasmlar</span><b>3</b><span>Video</span><b>4</b><span>3D sxema</span></nav></div></section>;
  if(phase==="result") return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>TAQQOSLASH</span><b>TAYYOR</b></div><div className="studio-compare-tabs"><button className={compare==="original"?"is-active":""} onClick={()=>setCompare("original")}>Original</button><button className={compare==="result"?"is-active":""} onClick={()=>setCompare("result")}>AI natija</button></div><div className={`studio-result ${compare==="result"?"is-result":""}`}>{source&&<><Image unoptimized src={source.url} alt="Mahsulot natijasi" width={900} height={700}/><span className="studio-result-floor"/></>}</div></section>;
  if(source) return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>ORIGINAL PREVIEW</span><b>YUKLANDI</b></div><div className="studio-result studio-source-preview"><Image unoptimized src={source.url} alt="Yuklangan mahsulot rasmi" width={900} height={700}/><span className="studio-result-floor"/></div></section>;
  return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>PREVIEW WORKSPACE</span><b>DEMO</b></div><div className="studio-empty-preview"><div><ScanLine size={34}/></div><strong>AI natija shu yerda ko‘rinadi</strong><span>Rasmni yuklang, formatni tanlang va tayyorlashni boshlang</span></div></section>;
}

function SnowUnit(){return <div className="studio-unit" aria-label="Sovutish qurilmasi maketi"><div className="studio-unit-top"/><div className="studio-fan"><span/><span/><span/><span/></div><div className="studio-fan second"><span/><span/><span/><span/></div><i/><i/></div>}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:()=>void}){return <button type="button" className="studio-toggle-row" onClick={onChange}><span>{label}</span><i className={checked?"is-on":""}/></button>}
function Controls({mode,ready,phase,onGenerate}:{mode:Mode;ready:boolean;phase:Phase;onGenerate:()=>void}){
 const [background,setBackground]=useState("white"),[size,setSize]=useState(mode==="360"?"2000":"1500"),[protect,setProtect]=useState(true),[open,setOpen]=useState(false);const [toggles,setToggles]=useState([true,true,true,true]);
 return <section className="studio-card studio-controls"><div className="studio-section-title"><div><span>02</span><h2>Sozlamalar</h2></div></div><label>NATIJA FONI</label><div className="studio-segment">{[["white","Oq fon"],["transparent","Transparent"],["original","Original+"]].map(([v,l])=><button key={v} className={background===v?"is-active":""} onClick={()=>setBackground(v)}>{l}</button>)}</div><label>O‘LCHAM</label><div className="studio-size-options">{["1000","1500","2000"].map(v=><button key={v} className={size===v?"is-active":""} onClick={()=>setSize(v)}>{v} × {v}</button>)}</div><label>YAXSHILASH</label><div className="studio-toggles">{["Fonini tozalash","Rasm sifatini yaxshilash","Ranglarni to‘g‘rilash","Soya va yorug‘lik"].map((label,i)=><Toggle key={label} label={label} checked={toggles[i]} onChange={()=>setToggles(s=>s.map((v,n)=>n===i?!v:v))}/>)}</div><div className="studio-protection"><div><span><ShieldCheck size={17}/>MAHSULOTNI HIMOYA QILISH</span><button onClick={()=>setProtect(!protect)}><i className={protect?"is-on":""}/></button></div><p>AI mahsulotning original texnik ko‘rinishini imkon qadar saqlaydi.</p><small>AI faqat vizual sifat, fon va yorug‘likni yaxshilaydi.</small><button className="studio-checklist-toggle" onClick={()=>setOpen(!open)}>Himoya elementlari <ChevronDown className={open?"is-open":""} size={15}/></button>{open&&<ul>{["Logo","Model yozuvi","Fanlar soni","Quvurlar","Korpus geometriyasi","Asosiy komponentlar"].map(x=><li key={x}><Check size={13}/>{x}</li>)}</ul>}</div><button className="studio-generate" disabled={!ready||phase==="processing"} onClick={onGenerate}>{phase==="processing"?<><RefreshCw className="is-spinning" size={17}/>Tayyorlanmoqda...</>:<><Sparkles size={17}/>{phase==="result"?"Qayta yaratish":"AI bilan tayyorlash"}</>}</button></section>
}

function SaveDialog({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:()=>void}){const [destination,setDestination]=useState("product");if(!open)return null;return <div className="studio-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="studio-modal" role="dialog" aria-modal="true" aria-labelledby="save-title"><button className="studio-modal-close" onClick={onClose}><X size={18}/></button><div className="studio-modal-icon"><PackageCheck/></div><h2 id="save-title">Tayyor rasmni saqlash</h2><p>Natijani qayerda ishlatishni tanlang.</p><div className="studio-save-options">{[["product","Mahsulotga biriktirish"],["projects","Loyihalarga saqlash"],["media","Media kutubxonaga saqlash"]].map(([v,l])=><button key={v} onClick={()=>setDestination(v)} className={destination===v?"is-active":""}><span>{destination===v&&<Check size={13}/>}</span>{l}</button>)}</div>{destination==="product"&&<div className="studio-product-select"><label>Mahsulot</label><select defaultValue="xue"><option value="xue">XUE YING BR +20PG</option><option>Bitzer 4TES-9Y</option><option>Carrier AquaSnap 30RA</option></select><div><label><input type="radio" name="placement" defaultChecked/> Asosiy rasm</label><label><input type="radio" name="placement"/> Galereyaga qo‘shish</label></div></div>}<button className="studio-modal-save" onClick={onSaved}>Saqlash</button><small>Demo rejimi — ma’lumotlar bazaga yozilmaydi</small></div></div>}

const recent=["XUE YING BR +20PG","Evaporator DD160","Bitzer 4TES-9Y","Carrier AquaSnap 30RA","Sovutish kamerasi"], recentModes=["Mahsulot kartasi","Transparent PNG","Reklama","Loyiha","Mahsulot sahifasi"];
export function PhotoStudioWorkspace(){
 const [mode,setMode]=useState<Mode>("card"),[source,setSourceState]=useState<StudioFile>(),[angles,setAngles]=useState<(StudioFile|undefined)[]>([undefined,undefined,undefined,undefined]),[phase,setPhase]=useState<Phase>("idle"),[compare,setCompare]=useState<"original"|"result">("result"),[dialog,setDialog]=useState(false),[toast,setToast]=useState(false);const timers=useRef<number[]>([]);useEffect(()=>()=>{timers.current.forEach(clearTimeout);},[]);
 const changeMode=(next:Mode)=>{setMode(next);setPhase("idle");};const setSource=(next?:StudioFile)=>{if(source)URL.revokeObjectURL(source.url);setSourceState(next);setPhase("idle");};const setAngle=(i:number,next?:StudioFile)=>{setAngles(current=>current.map((v,n)=>{if(n===i&&v)URL.revokeObjectURL(v.url);return n===i?next:v;}));setPhase("idle");};const ready=mode==="360"?angles.every(Boolean):Boolean(source);const generate=()=>{setPhase("processing");timers.current.push(window.setTimeout(()=>{setPhase("result");setCompare("result");},1500));};const saved=()=>{setDialog(false);setToast(true);timers.current.push(window.setTimeout(()=>setToast(false),2600));};
 return <div className="photo-studio-page"><header className="studio-heading"><div><span className="studio-ai-badge"><Sparkles size={12}/>AI CREATIVE WORKSPACE</span><h1>AI Foto Studio</h1><p>Oddiy mahsulot rasmlarini professional BUYUK KARAVAN vizualiga aylantiring.</p></div><div className="studio-steps"><span className="is-active">1 Yuklash</span><i/><span>2 Tayyorlash</span><i/><span>3 Tasdiqlash</span></div></header><nav className="studio-modes" aria-label="Studio rejimi">{modes.map(item=><button key={item.id} className={mode===item.id?"is-active":""} onClick={()=>changeMode(item.id)}>{item.id==="360"?<RotateCcw/>:item.id==="transparent"?<Layers3/>:item.id==="ad"?<Sparkles/>:<ImageIcon/>}<span>{item.label}</span>{mode===item.id&&<CheckCircle2/>}</button>)}</nav><div className="studio-workspace"><SourcePanel mode={mode} source={source} angles={angles} setSource={setSource} setAngle={setAngle}/><Preview mode={mode} phase={phase} source={source} compare={compare} setCompare={setCompare}/><Controls key={mode} mode={mode} ready={ready} phase={phase} onGenerate={generate}/>{phase==="result"&&<div className="studio-result-actions"><button onClick={generate}><RefreshCw size={15}/>Qayta yaratish</button>{mode!=="360"&&<button onClick={()=>setCompare(compare==="result"?"original":"result")}><Expand size={15}/>Original bilan solishtirish</button>}<button className="is-primary" onClick={()=>setDialog(true)}><Check size={15}/>Tasdiqlash</button></div>}</div><section className="studio-recent"><div><h2>Oxirgi ishlovlar</h2><span>Frontend demo tarixi</span></div><div className="studio-recent-grid">{recent.map((name,i)=><article key={name}><div><SnowUnit/></div><span><strong>{name}</strong><small>{recentModes[i]}</small></span><b><Check size={11}/>Tayyor</b></article>)}</div></section><SaveDialog open={dialog} onClose={()=>setDialog(false)} onSaved={saved}/>{toast&&<div className="studio-toast"><CheckCircle2 size={18}/><span><strong>Demo saqlandi</strong> Hech qanday real ma’lumot o‘zgartirilmadi.</span></div>}</div>
}
