"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { Check, CheckCircle2, ChevronDown, Expand, ImageIcon, Layers3, PackageCheck, RefreshCw, ScanLine, ShieldCheck, Sparkles, Trash2, UploadCloud, X } from "lucide-react";
import { processPhotoStudioImageAction, saveApprovedPhotoStudioImageAction } from "@/app/admin/(protected)/photo-studio/actions";
import type { PhotoStudioSettings } from "@/lib/photo-studio/types";

type Mode = "card" | "detail" | "project" | "transparent" | "ad";
type StudioFile = { file: File; url: string };
type Phase = "idle" | "processing" | "result";
type ProductOption = { id: string; name: string; model: string };
const modes: { id: Mode; label: string }[] = [
  { id: "card", label: "Mahsulot kartasi" }, { id: "detail", label: "Mahsulot sahifasi" },
  { id: "project", label: "Loyiha" },
  { id: "transparent", label: "Transparent PNG" }, { id: "ad", label: "Reklama" },
];

function FilePicker({ value, onChange }: { value?: StudioFile; onChange: (file?: StudioFile) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const pick = (file?: File) => {
    if (!file) return;
    if (!["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024) return;
    onChange({ file, url: URL.createObjectURL(file) });
  };
  if (value) return <div className="studio-file">
    <Image unoptimized src={value.url} alt={value.file.name} width={320} height={200}/>
    <span className="studio-file-check"><Check size={13}/></span>
    <div className="studio-file-meta"><strong>{value.file.name}</strong><small>{value.file.name}</small></div>
    <div className="studio-file-actions"><button type="button" onClick={() => input.current?.click()}>Almashtirish</button><button type="button" aria-label="Rasmni olib tashlash" onClick={() => onChange()}><Trash2 size={14}/></button></div>
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { pick(e.target.files?.[0]); e.target.value=""; }}/>
  </div>;
  return <div className="studio-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0]);}}>
    <UploadCloud size={28}/><span>Rasmni shu yerga tashlang</span><button type="button" onClick={()=>input.current?.click()}>Rasm tanlash</button><small>PNG, JPG, WebP · 10 MB gacha</small>
    <input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{pick(e.target.files?.[0]);e.target.value="";}}/>
  </div>;
}

function SourcePanel({ source, setSource }: { source?: StudioFile; setSource:(v?:StudioFile)=>void }) {
  return <section className="studio-card studio-sources"><div className="studio-section-title"><div><span>01</span><h2>Original rasmlar</h2></div></div><FilePicker value={source} onChange={setSource}/></section>;
}

function Preview({ phase, source, resultUrl, compare, setCompare }: { phase:Phase; source?:StudioFile; resultUrl?:string; compare:"original"|"result"; setCompare:(v:"original"|"result")=>void }) {
  if(phase==="processing") return <section className="studio-card studio-preview"><div className="studio-processing"><div className="studio-product-mock"><SnowUnit/></div><span className="studio-scan"/><Sparkles size={24}/><strong>AI mahsulot rasmini tayyorlamoqda...</strong><small>Fon, yorug‘lik va mahsulot aniqligi tekshirilmoqda</small></div></section>;
  if(phase==="result") return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>TAQQOSLASH</span><b>TAYYOR</b></div><div className="studio-compare-tabs"><button className={compare==="original"?"is-active":""} onClick={()=>setCompare("original")}>ORIGINAL</button><button className={compare==="result"?"is-active":""} onClick={()=>setCompare("result")}>NATIJA</button></div><div className={`studio-result ${compare==="result"?"is-result":""}`}>{source&&resultUrl&&<><Image unoptimized src={compare==="result"?resultUrl:source.url} alt={compare==="result"?"AI natijasi":"Original mahsulot rasmi"} width={900} height={700}/><span className="studio-result-floor"/></>}</div></section>;
  if(source) return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>ORIGINAL PREVIEW</span><b>YUKLANDI</b></div><div className="studio-result studio-source-preview"><Image unoptimized src={source.url} alt="Yuklangan mahsulot rasmi" width={900} height={700}/><span className="studio-result-floor"/></div></section>;
  return <section className="studio-card studio-preview"><div className="studio-preview-label"><span>PREVIEW WORKSPACE</span><b>DEMO</b></div><div className="studio-empty-preview"><div><ScanLine size={34}/></div><strong>AI natija shu yerda ko‘rinadi</strong><span>Rasmni yuklang, formatni tanlang va tayyorlashni boshlang</span></div></section>;
}

function SnowUnit(){return <div className="studio-unit" aria-label="Sovutish qurilmasi maketi"><div className="studio-unit-top"/><div className="studio-fan"><span/><span/><span/><span/></div><div className="studio-fan second"><span/><span/><span/><span/></div><i/><i/></div>}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:()=>void}){return <button type="button" className="studio-toggle-row" onClick={onChange}><span>{label}</span><i className={checked?"is-on":""}/></button>}
function Controls({ready,phase,settings,onSettings,onGenerate}:{ready:boolean;phase:Phase;settings:PhotoStudioSettings;onSettings:(next:PhotoStudioSettings)=>void;onGenerate:()=>void}){
 const [open,setOpen]=useState(false);const update=<K extends keyof PhotoStudioSettings>(key:K,value:PhotoStudioSettings[K])=>onSettings({...settings,[key]:value});
 const enhancements:[[keyof PhotoStudioSettings,string],...Array<[keyof PhotoStudioSettings,string]>]=[["removeBackground","Fonini tozalash"],["enhanceQuality","Rasm sifatini yaxshilash"],["correctColors","Ranglarni to‘g‘rilash"],["improveLighting","Soya va yorug‘lik"]];
 return <section className="studio-card studio-controls"><div className="studio-section-title"><div><span>02</span><h2>Sozlamalar</h2></div></div><label>NATIJA FONI</label><div className="studio-segment">{[["white","Oq fon"],["transparent","Transparent"],["original","Original+"]].map(([v,l])=><button key={v} className={settings.background===v?"is-active":""} onClick={()=>update("background",v as PhotoStudioSettings["background"])}>{l}</button>)}</div><label>O‘LCHAM</label><div className="studio-size-options">{[1000,1500,2000].map(v=><button key={v} className={settings.size===v?"is-active":""} onClick={()=>update("size",v as PhotoStudioSettings["size"])}>{v} × {v}</button>)}</div><label>YAXSHILASH</label><div className="studio-toggles">{enhancements.map(([key,label])=><Toggle key={key} label={label} checked={Boolean(settings[key])} onChange={()=>update(key,!settings[key] as never)}/>)}</div><div className="studio-protection"><div><span><ShieldCheck size={17}/>MAHSULOTNI HIMOYA QILISH</span><button onClick={()=>update("protectProduct",!settings.protectProduct)}><i className={settings.protectProduct?"is-on":""}/></button></div><p>AI mahsulotning original texnik ko‘rinishini imkon qadar saqlaydi.</p><small>AI faqat vizual sifat, fon va yorug‘likni yaxshilaydi.</small><button className="studio-checklist-toggle" onClick={()=>setOpen(!open)}>Himoya elementlari <ChevronDown className={open?"is-open":""} size={15}/></button>{open&&<ul>{["Logo","Model yozuvi","Fanlar soni","Quvurlar","Korpus geometriyasi","Asosiy komponentlar"].map(x=><li key={x}><Check size={13}/>{x}</li>)}</ul>}</div><button className="studio-generate" disabled={!ready||phase==="processing"} onClick={onGenerate}>{phase==="processing"?<><RefreshCw className="is-spinning" size={17}/>Tayyorlanmoqda...</>:<><Sparkles size={17}/>{phase==="result"?"Qayta yaratish":"AI bilan tayyorlash"}</>}</button></section>
}

function SaveDialog({open,image,products,onClose,onSaved}:{open:boolean;image?:string;products:ProductOption[];onClose:()=>void;onSaved:()=>void}) {
 const [productId,setProductId]=useState(products[0]?.id??"");const [placement,setPlacement]=useState<"main"|"gallery">("main");const [search,setSearch]=useState("");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 if(!open)return null;const filtered=products.filter(product=>`${product.name} ${product.model}`.toLocaleLowerCase("uz").includes(search.toLocaleLowerCase("uz")));const save=async()=>{if(!image||!productId)return;setSaving(true);setError("");const result=await saveApprovedPhotoStudioImageAction({productId,placement,image});setSaving(false);if(result.error){setError(result.error);return;}onSaved();};
 return <div className="studio-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="studio-modal" role="dialog" aria-modal="true" aria-labelledby="save-title"><button className="studio-modal-close" onClick={onClose}><X size={18}/></button><div className="studio-modal-icon"><PackageCheck/></div><h2 id="save-title">Tayyor rasmni saqlash</h2><p>Natijani qayerda ishlatishni tanlang.</p><div className="studio-save-options"><button className="is-active"><span><Check size={13}/></span>Mahsulotga biriktirish</button><button disabled><span/>Loyihalarga saqlash <small>Keyingi bosqichda</small></button><button disabled><span/>Media kutubxonaga saqlash <small>Keyingi bosqichda</small></button></div><div className="studio-product-select"><label>Mahsulot</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mahsulotni qidiring"/><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Mahsulotni tanlang</option>{filtered.map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select><div><label><input type="radio" name="placement" checked={placement==="main"} onChange={()=>setPlacement("main")}/> Asosiy rasm</label><label><input type="radio" name="placement" checked={placement==="gallery"} onChange={()=>setPlacement("gallery")}/> Galereyaga qo‘shish</label></div></div>{error&&<p className="studio-action-error" role="alert">{error}</p>}<button className="studio-modal-save" disabled={!image||!productId||saving} onClick={save}>{saving?"Saqlanmoqda...":"Saqlash"}</button><small>Rasm tasdiqlangandan keyingina Neon xotirasiga saqlanadi.</small></div></div>;
}

const recent=["XUE YING BR +20PG","Evaporator DD160","Bitzer 4TES-9Y","Carrier AquaSnap 30RA","Sovutish kamerasi"], recentModes=["Mahsulot kartasi","Transparent PNG","Reklama","Loyiha","Mahsulot sahifasi"];
export function PhotoStudioWorkspace({products}:{products:ProductOption[]}) {
 const initialSettings:PhotoStudioSettings={background:"white",size:1500,removeBackground:true,enhanceQuality:true,correctColors:true,improveLighting:true,protectProduct:true};
 const [mode,setMode]=useState<Mode>("card"),[source,setSourceState]=useState<StudioFile>(),[phase,setPhase]=useState<Phase>("idle"),[compare,setCompare]=useState<"original"|"result">("result"),[dialog,setDialog]=useState(false),[toast,setToast]=useState(false),[settings,setSettings]=useState<PhotoStudioSettings>(initialSettings),[resultImage,setResultImage]=useState<string>(),[feedback,setFeedback]=useState("");const timers=useRef<number[]>([]);useEffect(()=>()=>{timers.current.forEach(clearTimeout);},[]);
 const clearResult=()=>{setPhase("idle");setResultImage(undefined);setFeedback("");};const changeMode=(next:Mode)=>{setMode(next);setSettings(current=>({...current,size:1500}));clearResult();};const setSource=(next?:StudioFile)=>{if(source)URL.revokeObjectURL(source.url);setSourceState(next);clearResult();};const updateSettings=(next:PhotoStudioSettings)=>{setSettings(next);clearResult();};const ready=Boolean(source);
 const generate=async()=>{if(!source)return;setPhase("processing");setFeedback("");setResultImage(undefined);const form=new FormData();form.set("image",source.file);form.set("mode",mode);form.set("background",settings.background);form.set("size",String(settings.size));for(const key of ["removeBackground","enhanceQuality","correctColors","improveLighting","protectProduct"] as const)form.set(key,String(settings[key]));const result=await processPhotoStudioImageAction(form);if(result.error||!result.image){setPhase("idle");setFeedback(result.error??"Rasmni qayta ishlash amalga oshmadi.");return;}setResultImage(result.image);setCompare("result");setPhase("result");};const saved=()=>{setDialog(false);setToast(true);timers.current.push(window.setTimeout(()=>setToast(false),2600));};const resultUrl=resultImage?`data:image/png;base64,${resultImage}`:undefined;
 return <div className="photo-studio-page"><header className="studio-heading"><div><span className="studio-ai-badge"><Sparkles size={12}/>AI CREATIVE WORKSPACE</span><h1>AI Foto Studio</h1><p>Oddiy mahsulot rasmlarini professional BUYUK KARAVAN vizualiga aylantiring.</p></div><div className="studio-steps"><span className="is-active">1 Yuklash</span><i/><span>2 Tayyorlash</span><i/><span>3 Tasdiqlash</span></div></header><nav className="studio-modes" aria-label="Studio rejimi">{modes.map(item=><button key={item.id} className={mode===item.id?"is-active":""} onClick={()=>changeMode(item.id)}>{item.id==="transparent"?<Layers3/>:item.id==="ad"?<Sparkles/>:<ImageIcon/>}<span>{item.label}</span>{mode===item.id&&<CheckCircle2/>}</button>)}</nav><div className="studio-workspace"><SourcePanel source={source} setSource={setSource}/><Preview phase={phase} source={source} resultUrl={resultUrl} compare={compare} setCompare={setCompare}/><Controls ready={ready} phase={phase} settings={settings} onSettings={updateSettings} onGenerate={generate}/>{feedback&&<p className="studio-action-error" role="alert">{feedback}</p>}{phase==="result"&&<div className="studio-result-actions"><button onClick={generate}><RefreshCw size={15}/>Qayta yaratish</button><button onClick={()=>setCompare(compare==="result"?"original":"result")}><Expand size={15}/>Original bilan solishtirish</button><button className="is-primary" onClick={()=>setDialog(true)}><Check size={15}/>Tasdiqlash</button></div>}</div><section className="studio-recent"><div><h2>Oxirgi ishlovlar</h2><span>Oldingi natijalar</span></div><div className="studio-recent-grid">{recent.map((name,i)=><article key={name}><div><SnowUnit/></div><span><strong>{name}</strong><small>{recentModes[i]}</small></span><b><Check size={11}/>Tayyor</b></article>)}</div></section><SaveDialog open={dialog} image={resultImage} products={products} onClose={()=>setDialog(false)} onSaved={saved}/>{toast&&<div className="studio-toast"><CheckCircle2 size={18}/><span><strong>Rasm saqlandi</strong> Tasdiqlangan natija mahsulotga biriktirildi.</span></div>}</div>;
}
